import { AQUA, BOLD, COMMON, DARK_GRAY, EPIC, GOLD, GRAY, LEGENDARY, MYTHIC, OBFUSCATED, RARE, SPECIAL, UNCOMMON, WHITE } from "./formatting";

// itemId - ID of the item used by bazaar or auction APIs
// itemName - name without formatting used to understand what item is dropped
// itemDisplayName - name with formatting
// npcPrice - NPC price if exists, or 0

export const FISHING_PROFIT_ITEMS = [

    // Common

    {
        itemId: 'WORM_THE_FISH',
        itemName: 'Worm the Fish',
        itemDisplayName: `${SPECIAL}Worm the Fish`,
        npcPrice: 0,
    },
    {
        itemId: 'BOBBIN_SCRIPTURES',
        itemName: 'Bobbin\' Scriptures',
        itemDisplayName: `${RARE}Bobbin\' Scriptures`,
        npcPrice: 0,
    },
    {
        itemId: 'TITANIC_EXP_BOTTLE',
        itemName: 'Titanic Experience Bottle',
        itemDisplayName: `${RARE}Titanic Experience Bottle`,
        npcPrice: 5000,
    },
    {
        itemId: 'GRAND_EXP_BOTTLE',
        itemName: 'Grand Experience Bottle',
        itemDisplayName: `${UNCOMMON}Grand Experience Bottle`,
        npcPrice: 480,
    },
    {
        itemId: 'CARNIVAL_TICKET',
        itemName: 'Carnival Ticket',
        itemDisplayName: `${UNCOMMON}Carnival Ticket`,
        npcPrice: 0,
    },

    // Water

    {
        itemId: 'CHUM',
        itemName: 'Chum',
        itemDisplayName: `${UNCOMMON}Chum`,
        npcPrice: 0,
    },
    {
        itemId: 'WATER_LILY',
        itemName: 'Lily Pad',
        itemDisplayName: `${COMMON}Lily Pad`,
        npcPrice: 10,
    },
    {
        itemId: 'ENCHANTED_WATER_LILY',
        itemName: 'Enchanted Lily Pad',
        itemDisplayName: `${UNCOMMON}Enchanted Lily Pad`,
        npcPrice: 1600,
    },
    {
        itemId: 'INK_SACK',
        itemName: 'Ink Sac',
        itemDisplayName: `${COMMON}Ink Sac`,
        npcPrice: 2,
    },
    {
        itemId: 'PRISMARINE_CRYSTALS',
        itemName: 'Prismarine Crystals',
        itemDisplayName: `${COMMON}Prismarine Crystals`,
        npcPrice: 5,
    },
    {
        itemId: 'ENCHANTED_PRISMARINE_CRYSTALS',
        itemName: 'Enchanted Prismarine Crystals',
        itemDisplayName: `${UNCOMMON}Enchanted Prismarine Crystals`,
        npcPrice: 400,
    },
    {
        itemId: 'PRISMARINE_SHARD',
        itemName: 'Prismarine Shard',
        itemDisplayName: `${COMMON}Prismarine Shard`,
        npcPrice: 5,
    },
    {
        itemId: 'ENCHANTED_PRISMARINE_SHARD',
        itemName: 'Enchanted Prismarine Shard',
        itemDisplayName: `${UNCOMMON}Enchanted Prismarine Shard`,
        npcPrice: 400,
    },
    {
        itemId: 'RAW_FISH',
        itemName: 'Raw Fish',
        itemDisplayName: `${COMMON}Raw Fish`,
        npcPrice: 6,
    },
    {
        itemId: 'RAW_FISH:1',
        itemName: 'Raw Salmon',
        itemDisplayName: `${COMMON}Raw Salmon`,
        npcPrice: 10,
    },
    {
        itemId: 'RAW_FISH:2',
        itemName: 'Clownfish',
        itemDisplayName: `${COMMON}Clownfish`,
        npcPrice: 20,
    },
    {
        itemId: 'RAW_FISH:3',
        itemName: 'Pufferfish',
        itemDisplayName: `${COMMON}Pufferfish`,
        npcPrice: 15,
    },
    {
        itemId: 'ENCHANTED_PUFFERFISH',
        itemName: 'Enchanted Pufferfish',
        itemDisplayName: `${UNCOMMON}Enchanted Pufferfish`,
        npcPrice: 2400,
    },
    {
        itemId: 'SPONGE',
        itemName: 'Sponge',
        itemDisplayName: `${COMMON}Sponge`,
        npcPrice: 50,
    },
    {
        itemId: 'CLAY_BALL',
        itemName: 'Clay',
        itemDisplayName: `${COMMON}Clay`,
        npcPrice: 3,
    },
    {
        itemId: 'ENCHANTED_CLAY_BALL',
        itemName: 'Enchanted Clay',
        itemDisplayName: `${UNCOMMON}Enchanted Clay`,
        npcPrice: 480,
    },
    {
        itemId: 'Guardian;0',
        itemName: '[Lvl 1] Guardian (COMMON)',
        itemDisplayName: `${COMMON}Guardian`,
        npcPrice: 100,
    },
    {
        itemId: 'Guardian;1',
        itemName: '[Lvl 1] Guardian (UNCOMMON)',
        itemDisplayName: `${UNCOMMON}Guardian`,
        npcPrice: 500,
    },
    {
        itemId: 'Guardian;2',
        itemName: '[Lvl 1] Guardian (RARE)',
        itemDisplayName: `${RARE}Guardian`,
        npcPrice: 1000,
    },
    {
        itemId: 'Guardian;3',
        itemName: '[Lvl 1] Guardian (EPIC)',
        itemDisplayName: `${EPIC}Guardian`,
        npcPrice: 100000,
    },
    {
        itemId: 'Guardian;4',
        itemName: '[Lvl 1] Guardian (LEGENDARY)',
        itemDisplayName: `${LEGENDARY}Guardian`,
        npcPrice: 250000,
    },
    {
        itemId: 'Squid;0',
        itemName: '[Lvl 1] Squid (COMMON)',
        itemDisplayName: `${COMMON}Squid`,
        npcPrice: 100,
    },
    {
        itemId: 'Squid;1',
        itemName: '[Lvl 1] Squid (UNCOMMON)',
        itemDisplayName: `${UNCOMMON}Squid`,
        npcPrice: 500,
    },
    {
        itemId: 'Squid;2',
        itemName: '[Lvl 1] Squid (RARE)',
        itemDisplayName: `${RARE}Squid`,
        npcPrice: 100000,
    },
    {
        itemId: 'Squid;3',
        itemName: '[Lvl 1] Squid (EPIC)',
        itemDisplayName: `${EPIC}Squid`,
        npcPrice: 200000,
    },
    {
        itemId: 'Squid;4',
        itemName: '[Lvl 1] Squid (LEGENDARY)',
        itemDisplayName: `${LEGENDARY}Squid`,
        npcPrice: 500000,
    },
    {
        itemId: 'BONE',
        itemName: 'Bone',
        itemDisplayName: `${COMMON}Bone`,
        npcPrice: 2,
    },
    {
        itemId: 'ENCHANTED_BONE',
        itemName: 'Enchanted Bone',
        itemDisplayName: `${UNCOMMON}Enchanted Bone`,
        npcPrice: 320,
    },
    {
        itemId: 'SEA_LANTERN',
        itemName: 'Sea Lantern',
        itemDisplayName: `${COMMON}Sea Lantern`,
        npcPrice: 45,
    },
    {
        itemId: 'ROTTEN_FLESH',
        itemName: 'Rotten Flesh',
        itemDisplayName: `${COMMON}Rotten Flesh`,
        npcPrice: 2,
    },
    {
        itemId: 'ENCHANTED_ROTTEN_FLESH',
        itemName: 'Enchanted Rotten Flesh',
        itemDisplayName: `${UNCOMMON}Enchanted Rotten Flesh`,
        npcPrice: 320,
    },
    {
        itemId: 'ENCHANTED_FEATHER',
        itemName: 'Enchanted Feather',
        itemDisplayName: `${UNCOMMON}Enchanted Feather`,
        npcPrice: 480,
    },
    {
        itemId: 'ENCHANTED_IRON',
        itemName: 'Enchanted Iron',
        itemDisplayName: `${UNCOMMON}Enchanted Iron`,
        npcPrice: 480,
    },
    {
        itemId: 'ENCHANTED_GOLD',
        itemName: 'Enchanted Gold',
        itemDisplayName: `${UNCOMMON}Enchanted Gold`,
        npcPrice: 640,
    },
    {
        itemId: 'ENCHANTED_DIAMOND',
        itemName: 'Enchanted Diamond',
        itemDisplayName: `${UNCOMMON}Enchanted Diamond`,
        npcPrice: 1280,
    },
    {
        itemId: 'RED_MUSHROOM',
        itemName: 'Red Mushroom',
        itemDisplayName: `${COMMON}Red Mushroom`,
        npcPrice: 10,
    },
    {
        itemId: 'FAIRY_HELMET',
        itemName: 'Fairy\'s Fedora',
        itemDisplayName: `${RARE}Fairy's Fedora`,
        npcPrice: 420,
    },
    {
        itemId: 'FAIRY_CHESTPLATE',
        itemName: 'Fairy\'s Polo',
        itemDisplayName: `${RARE}Fairy's Polo`,
        npcPrice: 420,
    },
    {
        itemId: 'FAIRY_LEGGINGS',
        itemName: 'Fairy\'s Trousers',
        itemDisplayName: `${RARE}Fairy's Trousers`,
        npcPrice: 420,
    },
    {
        itemId: 'FAIRY_BOOTS',
        itemName: 'Fairy\'s Galoshes',
        itemDisplayName: `${RARE}Fairy's Galoshes`,
        npcPrice: 420,
    },
    {
        itemId: 'SQUID_BOOTS',
        itemName: 'Squid Boots',
        itemDisplayName: `${UNCOMMON}Squid Boots`,
        npcPrice: 15,
    },
    {
        itemId: 'AGARIMOO_TONGUE',
        itemName: 'Agarimoo Tongue',
        itemDisplayName: `${RARE}Agarimoo Tongue`,
        npcPrice: 2050,
    },
    {
        itemId: 'ENCHANTMENT_CORRUPTION_1',
        itemName: 'Enchanted Book (Corruption I)',
        itemDisplayName: `${RARE}Corruption I ${WHITE}Book`,
        npcPrice: 0,
    },
    {
        itemId: 'ENCHANTMENT_MAGNET_6',
        itemName: 'Enchanted Book (Magnet VI)',
        itemDisplayName: `${RARE}Magnet VI ${WHITE}Book`,
        npcPrice: 0,
    },
    {
        itemId: 'ENCHANTMENT_FRAIL_6',
        itemName: 'Enchanted Book (Frail VI)',
        itemDisplayName: `${RARE}Frail VI ${WHITE}Book`,
        npcPrice: 0,
    },
    {
        itemId: 'ENCHANTMENT_LURE_6',
        itemName: 'Enchanted Book (Lure VI)',
        itemDisplayName: `${RARE}Lure VI ${WHITE}Book`,
        npcPrice: 0,
    },
    {
        itemId: 'ENCHANTMENT_ANGLER_6',
        itemName: 'Enchanted Book (Angler VI)',
        itemDisplayName: `${RARE}Angler VI ${WHITE}Book`,
        npcPrice: 0,
    },
    {
        itemId: 'ENCHANTMENT_SPIKED_HOOK_6',
        itemName: 'Enchanted Book (Spiked Hook VI)',
        itemDisplayName: `${RARE}Spiked Hook VI ${WHITE}Book`,
        npcPrice: 0,
    },
    {
        itemId: 'ENCHANTMENT_LUCK_OF_THE_SEA_6',
        itemName: 'Enchanted Book (Luck of the Sea VI)',
        itemDisplayName: `${RARE}Luck of the Sea VI ${WHITE}Book`,
        npcPrice: 0,
    },
    {
        itemId: 'ENCHANTMENT_CASTER_6',
        itemName: 'Enchanted Book (Caster VI)',
        itemDisplayName: `${RARE}Caster VI ${WHITE}Book`,
        npcPrice: 0,
    },
    {
        itemId: 'ENCHANTMENT_BLESSING_6',
        itemName: 'Enchanted Book (Blessing VI)',
        itemDisplayName: `${RARE}Blessing VI ${WHITE}Book`,
        npcPrice: 0,
    },
    {
        itemId: 'CARROT',
        itemName: 'Carrot',
        itemDisplayName: `${COMMON}Carrot`,
        npcPrice: 3,
    },
    {
        itemId: 'ENCHANTED_CARROT',
        itemName: 'Enchanted Carrot',
        itemDisplayName: `${UNCOMMON}Enchanted Carrot`,
        npcPrice: 480,
    },
    {
        itemId: 'WOOL',
        itemName: 'White Wool',
        itemDisplayName: `${COMMON}White Wool`,
        npcPrice: 2,
    },
    {
        itemId: 'MUTTON',
        itemName: 'Mutton',
        itemDisplayName: `${COMMON}Mutton`,
        npcPrice: 5,
    },
    {
        itemId: 'ENCHANTED_MUTTON',
        itemName: 'Enchanted Mutton',
        itemDisplayName: `${UNCOMMON}Enchanted Mutton`,
        npcPrice: 800,
    },
    {
        itemId: 'ENCHANTED_COOKED_MUTTON',
        itemName: 'Enchanted Cooked Mutton',
        itemDisplayName: `${RARE}Enchanted Cooked Mutton`,
        npcPrice: 128000,
    },
    {
        itemId: 'RABBIT',
        itemName: 'Raw Rabbit',
        itemDisplayName: `${COMMON}Raw Rabbit`,
        npcPrice: 4,
    },
    {
        itemId: 'ENCHANTED_RABBIT',
        itemName: 'Enchanted Raw Rabbit',
        itemDisplayName: `${UNCOMMON}Enchanted Raw Rabbit`,
        npcPrice: 640,
    },
    {
        itemId: 'RABBIT_HIDE',
        itemName: 'Rabbit Hide',
        itemDisplayName: `${COMMON}Rabbit Hide`,
        npcPrice: 5,
    },
    {
        itemId: 'RABBIT_FOOT',
        itemName: 'Rabbit\'s Foot',
        itemDisplayName: `${COMMON}Rabbit's Foot`,
        npcPrice: 5,
    },
    {
        itemId: 'ENCHANTED_RABBIT_FOOT',
        itemName: 'Enchanted Rabbit Foot',
        itemDisplayName: `${UNCOMMON}Enchanted Rabbit Foot`,
        npcPrice: 800,
    },
    {
        itemId: 'RABBIT_HAT',
        itemName: 'Rabbit Hat',
        itemDisplayName: `${UNCOMMON}Rabbit Hat`,
        npcPrice: 10,
    },
    {
        itemId: 'PET_ITEM_LUCKY_CLOVER_DROP',
        itemName: 'Lucky Clover Core',
        itemDisplayName: `${EPIC}Lucky Clover Core`,
        npcPrice: 0,
    },
    {
        itemId: 'PET_ITEM_FISHING_SKILL_BOOST_UNCOMMON',
        itemName: 'Fishing Exp Boost (UNCOMMON)',
        itemDisplayName: `${UNCOMMON}Fishing Exp Boost`,
        npcPrice: 0,
    },
    {
        itemId: 'PET_ITEM_FISHING_SKILL_BOOST_RARE',
        itemName: 'Fishing Exp Boost (RARE)',
        itemDisplayName: `${RARE}Fishing Exp Boost`,
        npcPrice: 0,
    },
    {
        itemId: 'PET_ITEM_FISHING_SKILL_BOOST_EPIC',
        itemName: 'Fishing Exp Boost (EPIC)',
        itemDisplayName: `${EPIC}Fishing Exp Boost`,
        npcPrice: 0,
    },
    {
        itemId: 'WATER_HYDRA_HEAD',
        itemName: 'Water Hydra Head',
        itemDisplayName: `${EPIC}Water Hydra Head`,
        npcPrice: 500,
    },
    {
        itemId: 'FISH_AFFINITY_TALISMAN',
        itemName: 'Fish Affinity Talisman',
        itemDisplayName: `${RARE}Fish Affinity Talisman`,
        npcPrice: 1000,
    },
    {
        itemId: 'THE_SHREDDER',
        itemName: 'Shredder',
        itemDisplayName: `${LEGENDARY}Shredder`,
        npcPrice: 1000,
    },
    {
        itemId: 'DIVER_FRAGMENT',
        itemName: 'Emperor\'s Skull',
        itemDisplayName: `${RARE}Emperor's Skull`,
        npcPrice: 100,
    },
    {
        itemId: 'FLYING_FISH;2',
        itemName: '[Lvl 1] Flying Fish (RARE)',
        itemDisplayName: `${RARE}Flying Fish`,
        npcPrice: 0,
    },
    {
        itemId: 'FLYING_FISH;3',
        itemName: '[Lvl 1] Flying Fish (EPIC)',
        itemDisplayName: `${EPIC}Flying Fish`,
        npcPrice: 100000,
    },
    {
        itemId: 'FLYING_FISH;4',
        itemName: '[Lvl 1] Flying Fish (LEGENDARY)',
        itemDisplayName: `${LEGENDARY}Flying Fish`,
        npcPrice: 250000,
    },
    {
        itemId: 'DYE_AQUAMARINE',
        itemName: 'Aquamarine Dye',
        itemDisplayName: `${EPIC}Aquamarine Dye`,
        npcPrice: 0,
    },
    {
        itemId: 'DYE_ICEBERG',
        itemName: 'Iceberg Dye',
        itemDisplayName: `${EPIC}Iceberg Dye`,
        npcPrice: 0,
    },
    {
        itemId: 'DYE_NADESHIKO',
        itemName: 'Nadeshiko Dye',
        itemDisplayName: `${EPIC}Nadeshiko Dye`,
        npcPrice: 0,
    },

    // Crimson Isle

    {
        itemId: 'LUMP_OF_MAGMA',
        itemName: 'Lump of Magma',
        itemDisplayName: `${UNCOMMON}Lump of Magma`,
        npcPrice: 50,
    },
    {
        itemId: 'MOOGMA_PELT',
        itemName: 'Moogma Pelt',
        itemDisplayName: `${UNCOMMON}Moogma Pelt`,
        npcPrice: 50,
    },
    {
        itemId: 'CUP_OF_BLOOD',
        itemName: 'Cup of Blood',
        itemDisplayName: `${UNCOMMON}Cup of Blood`,
        npcPrice: 200,
    },
    {
        itemId: 'PYROCLASTIC_SCALE',
        itemName: 'Pyroclastic Scale',
        itemDisplayName: `${UNCOMMON}Pyroclastic Scale`,
        npcPrice: 50,
    },
    {
        itemId: 'FLAMING_HEART',
        itemName: 'Flaming Heart',
        itemDisplayName: `${RARE}Flaming Heart`,
        npcPrice: 200,
    },
    {
        itemId: 'ORB_OF_ENERGY',
        itemName: 'Orb of Energy',
        itemDisplayName: `${RARE}Orb of Energy`,
        npcPrice: 200,
    },
    {
        itemId: 'HORN_OF_TAURUS',
        itemName: 'Horn of Taurus',
        itemDisplayName: `${EPIC}Horn of Taurus`,
        npcPrice: 500,
    },
    {
        itemId: 'THUNDER_SHARDS',
        itemName: 'Thunder Shards',
        itemDisplayName: `${EPIC}Thunder Shards`,
        npcPrice: 50000,
    },
    {
        itemId: 'MAGMA_FISH',
        itemName: 'Magmafish',
        itemDisplayName: `${RARE}Magmafish`,
        npcPrice: 20,
    },
    {
        itemId: 'MAGMA_FISH_SILVER',
        itemName: 'Silver Magmafish',
        itemDisplayName: `${EPIC}Silver Magmafish`,
        npcPrice: 1600,
    },
    {
        itemId: 'LAVA_SHELL',
        itemName: 'Lava Shell',
        itemDisplayName: `${EPIC}Lava Shell`,
        npcPrice: 3000,
    },
    {
        itemId: 'NETHER_STAR',
        itemName: 'Nether Star',
        itemDisplayName: `${UNCOMMON}Nether Star`,
        npcPrice: 10000,
    },
    {
        itemId: 'SLUG_BOOTS',
        itemName: 'Slug Boots',
        itemDisplayName: `${RARE}Slug Boots`,
        npcPrice: 5000,
    },
    {
        itemId: 'MOOGMA_LEGGINGS',
        itemName: 'Moogma Leggings',
        itemDisplayName: `${RARE}Moogma Leggings`,
        npcPrice: 10000,
    },
    {
        itemId: 'FLAMING_CHESTPLATE',
        itemName: 'Flaming Chestplate',
        itemDisplayName: `${RARE}Flaming Chestplate`,
        npcPrice: 25000,
    },
    {
        itemId: 'TAURUS_HELMET',
        itemName: 'Taurus Helmet',
        itemDisplayName: `${RARE}Taurus Helmet`,
        npcPrice: 50000,
    },
    {
        itemId: 'TAURUS_HELMET',
        itemName: 'Taurus Helmet',
        itemDisplayName: `${RARE}Taurus Helmet`,
        npcPrice: 50000,
    },
    {
        itemId: 'BLADE_OF_THE_VOLCANO',
        itemName: 'Blade of the Volcano',
        itemDisplayName: `${RARE}Blade of the Volcano`,
        npcPrice: 5000,
    },
    {
        itemId: 'STAFF_OF_THE_VOLCANO',
        itemName: 'Staff of the Volcano',
        itemDisplayName: `${RARE}Staff of the Volcano`,
        npcPrice: 5000,
    },
    {
        itemId: 'PITCHIN_KOI',
        itemName: 'Pitchin\' Koi',
        itemDisplayName: `${RARE}Pitchin\' Koi`,
        npcPrice: 22222,
    },
    {
        itemId: 'MAGMA_LORD_FRAGMENT',
        itemName: 'Magma Lord Fragment',
        itemDisplayName: `${LEGENDARY}Magma Lord Fragment`,
        npcPrice: 0,
    },
    {
        itemId: 'RADIOACTIVE_VIAL',
        itemName: 'Radioactive Vial',
        itemDisplayName: `${MYTHIC}Radioactive Vial`,
        npcPrice: 100000,
    },
    {
        itemId: 'ENCHANTMENT_CHARM_1',
        itemName: 'Enchanted Book (Charm I)',
        itemDisplayName: `${RARE}Charm I ${WHITE}Book`,
        npcPrice: 0,
    },
    {
        itemId: 'ENCHANTMENT_ULTIMATE_FLASH_1',
        itemName: 'Enchanted Book (Flash I)',
        itemDisplayName: `${MYTHIC}${BOLD}Flash I ${WHITE}Book`,
        npcPrice: 0,
    },
    {
        itemId: 'ATTRIBUTE_SHARD+ATTRIBUTE_BLAZING_FORTUNE;1',
        itemName: 'Attribute Shard (Blazing Fortune I)',
        itemDisplayName: `${AQUA}Blazing Fortune I ${WHITE}Attribute Shard`,
        npcPrice: 0,
    },
    {
        itemId: 'ATTRIBUTE_SHARD+ATTRIBUTE_DOUBLE_HOOK;1',
        itemName: 'Attribute Shard (Double Hook I)',
        itemDisplayName: `${AQUA}Double Hook I ${WHITE}Attribute Shard`,
        npcPrice: 0,
    },
    {
        itemId: 'ATTRIBUTE_SHARD+ATTRIBUTE_FISHERMAN;1',
        itemName: 'Attribute Shard (Fisherman I)',
        itemDisplayName: `${AQUA}Fisherman I ${WHITE}Attribute Shard`,
        npcPrice: 0,
    },
    {
        itemId: 'ATTRIBUTE_SHARD+ATTRIBUTE_FISHING_EXPERIENCE;1',
        itemName: 'Attribute Shard (Fishing Experience I)',
        itemDisplayName: `${AQUA}Fishing Experience I ${WHITE}Attribute Shard`,
        npcPrice: 0,
    },
    {
        itemId: 'ATTRIBUTE_SHARD+ATTRIBUTE_FISHING_SPEED;1',
        itemName: 'Attribute Shard (Fishing Speed I)',
        itemDisplayName: `${AQUA}Fishing Speed I ${WHITE}Attribute Shard`,
        npcPrice: 0,
    },
    {
        itemId: 'ATTRIBUTE_SHARD+ATTRIBUTE_HUNTER;1',
        itemName: 'Attribute Shard (Hunter I)',
        itemDisplayName: `${AQUA}Hunter I ${WHITE}Attribute Shard`,
        npcPrice: 0,
    },
    {
        itemId: 'ATTRIBUTE_SHARD+ATTRIBUTE_INFECTION;1',
        itemName: 'Attribute Shard (Infection I)',
        itemDisplayName: `${AQUA}Infection I ${WHITE}Attribute Shard`,
        npcPrice: 0,
    },
    {
        itemId: 'ATTRIBUTE_SHARD+ATTRIBUTE_TROPHY_HUNTER;1',
        itemName: 'Attribute Shard (Trophy Hunter I)',
        itemDisplayName: `${AQUA}Trophy Hunter I ${WHITE}Attribute Shard`,
        npcPrice: 0,
    },

    // Crystal Hollows

    {
        itemId: 'HARD_STONE',
        itemName: 'Hard Stone',
        itemDisplayName: `${RARE}Hard Stone`,
        npcPrice: 1,
    },
    {
        itemId: 'BLAZE_ROD',
        itemName: 'Blaze Rod',
        itemDisplayName: `${COMMON}Blaze Rod`,
        npcPrice: 9,
    },
    {
        itemId: 'MAGMA_CORE',
        itemName: 'Magma Core',
        itemDisplayName: `${RARE}Magma Core`,
        npcPrice: 0,
    },
    {
        itemId: 'ENCHANTMENT_PISCARY_6',
        itemName: 'Enchanted Book (Piscary VI)',
        itemDisplayName: `${RARE}Piscary VI ${WHITE}Book`,
        npcPrice: 0,
    },
    {
        itemId: 'WORM_MEMBRANE',
        itemName: 'Worm Membrane',
        itemDisplayName: `${UNCOMMON}Worm Membrane`,
        npcPrice: 0,
    },
    {
        itemId: 'ETERNAL_FLAME_RING',
        itemName: 'Eternal Flame Ring',
        itemDisplayName: `${UNCOMMON}Eternal Flame Ring`,
        npcPrice: 0,
    },
    {
        itemId: 'ROUGH_JADE_GEM',
        itemName: 'Rough Jade Gemstone',
        itemDisplayName: `${COMMON}Rough Jade Gemstone`,
        npcPrice: 3,
    },
    {
        itemId: 'ROUGH_AMETHYST_GEM',
        itemName: 'Rough Amethyst Gemstone',
        itemDisplayName: `${COMMON}Rough Amethyst Gemstone`,
        npcPrice: 3,
    },
    {
        itemId: 'ROUGH_AMBER_GEM',
        itemName: 'Rough Amber Gemstone',
        itemDisplayName: `${COMMON}Rough Amber Gemstone`,
        npcPrice: 3,
    },
    {
        itemId: 'ROUGH_SAPPHIRE_GEM',
        itemName: 'Rough Sapphire Gemstone',
        itemDisplayName: `${COMMON}Rough Sapphire Gemstone`,
        npcPrice: 3,
    },
    {
        itemId: 'ROUGH_TOPAZ_GEM',
        itemName: 'Rough Topaz Gemstone',
        itemDisplayName: `${COMMON}Rough Topaz Gemstone`,
        npcPrice: 3,
    },
    {
        itemId: 'FLAWED_JADE_GEM',
        itemName: 'Flawed Jade Gemstone',
        itemDisplayName: `${UNCOMMON}Flawed Jade Gemstone`,
        npcPrice: 3,
    },
    {
        itemId: 'FLAWED_SAPPHIRE_GEM',
        itemName: 'Flawed Sapphire Gemstone',
        itemDisplayName: `${UNCOMMON}Flawed Sapphire Gemstone`,
        npcPrice: 3,
    },
    {
        itemId: 'FLAWED_AMETHYST_GEM',
        itemName: 'Flawed Amethyst Gemstone',
        itemDisplayName: `${UNCOMMON}Flawed Amethyst Gemstone`,
        npcPrice: 3,
    },
    {
        itemId: 'DYE_CARMINE',
        itemName: 'Carmine Dye',
        itemDisplayName: `${EPIC}Carmine Dye`,
        npcPrice: 0,
    },
    {
        itemId: 'DYE_FLAME',
        itemName: 'Flame Dye',
        itemDisplayName: `${EPIC}Flame Dye`,
        npcPrice: 0,
    },

    // Spooky

    {
        itemId: 'HAY_BLOCK',
        itemName: 'Hay Bale',
        itemDisplayName: `${COMMON}Hay Bale`,
        npcPrice: 24,
    },
    {
        itemId: 'GREEN_CANDY',
        itemName: 'Green Candy',
        itemDisplayName: `${UNCOMMON}Green Candy`,
        npcPrice: 0,
    },
    {
        itemId: 'PURPLE_CANDY',
        itemName: 'Purple Candy',
        itemDisplayName: `${EPIC}Purple Candy`,
        npcPrice: 0,
    },
    {
        itemId: 'LUCKY_HOOF',
        itemName: 'Lucky Hoof',
        itemDisplayName: `${UNCOMMON}Lucky Hoof`,
        npcPrice: 0,
    },
    {
        itemId: 'WEREWOLF_SKIN',
        itemName: 'Werewolf Skin',
        itemDisplayName: `${RARE}Werewolf Skin`,
        npcPrice: 0,
    },
    {
        itemId: 'DEEP_SEA_ORB',
        itemName: 'Deep Sea Orb',
        itemDisplayName: `${EPIC}Deep Sea Orb`,
        npcPrice: 0,
    },
    {
        itemId: 'PHANTOM_ROD',
        itemName: 'Phantom Rod',
        itemDisplayName: `${LEGENDARY}Phantom Rod`,
        npcPrice: 1000,
    },
    {
        itemId: 'SOUL_FRAGMENT',
        itemName: 'Soul Fragment',
        itemDisplayName: `${EPIC}Soul Fragment`,
        npcPrice: 0,
    },
    {
        itemId: 'PET_ITEM_VAMPIRE_FANG',
        itemName: 'Vampire Fang',
        itemDisplayName: `${LEGENDARY}Vampire Fang`,
        npcPrice: 0,
    },

    // Winter

    {
        itemId: 'ICE',
        itemName: 'Ice',
        itemDisplayName: `${COMMON}Ice`,
        npcPrice: 0.5,
    },
    {
        itemId: 'PACKED_ICE',
        itemName: 'Packed Ice',
        itemDisplayName: `${COMMON}Packed Ice`,
        npcPrice: 4.5,
    },
    {
        itemId: 'ENCHANTED_ICE',
        itemName: 'Enchanted Ice',
        itemDisplayName: `${UNCOMMON}Enchanted Ice`,
        npcPrice: 80,
    },
    {
        itemId: 'ENCHANTED_PACKED_ICE',
        itemName: 'Enchanted Packed Ice',
        itemDisplayName: `${RARE}Enchanted Packed Ice`,
        npcPrice: 12800,
    },
    {
        itemId: 'SNOWFLAKE_THE_FISH',
        itemName: 'Flake the Fish',
        itemDisplayName: `${COMMON}Flake the Fish`,
        npcPrice: 0,
    },
    {
        itemId: 'SNOW_BALL',
        itemName: 'Snowball',
        itemDisplayName: `${COMMON}Snowball`,
        npcPrice: 1,
    },
    {
        itemId: 'SNOW_BLOCK',
        itemName: 'Snow Block',
        itemDisplayName: `${COMMON}Snow Block`,
        npcPrice: 4,
    },
    {
        itemId: 'WALNUT',
        itemName: 'Walnut',
        itemDisplayName: `${UNCOMMON}Walnut`,
        npcPrice: 200,
    },
    {
        itemId: 'WHITE_GIFT',
        itemName: 'White Gift',
        itemDisplayName: `${COMMON}White Gift`,
        npcPrice: 0,
    },
    {
        itemId: 'GREEN_GIFT',
        itemName: 'Green Gift',
        itemDisplayName: `${UNCOMMON}Green Gift`,
        npcPrice: 0,
    },
    {
        itemId: 'RED_GIFT',
        itemName: 'Red Gift',
        itemDisplayName: `${RARE}Red Gift`,
        npcPrice: 0,
    },
    {
        itemId: 'ICE_HUNK',
        itemName: 'Hunk of Ice',
        itemDisplayName: `${UNCOMMON}Hunk of Ice`,
        npcPrice: 0,
    },
    {
        itemId: 'BLUE_ICE_HUNK',
        itemName: 'Hunk of Blue Ice',
        itemDisplayName: `${RARE}Hunk of Blue Ice`,
        npcPrice: 0,
    },
    {
        itemId: 'YETI_ROD',
        itemName: 'Yeti Rod',
        itemDisplayName: `${EPIC}Yeti Rod`,
        npcPrice: 150000,
    },
    {
        itemId: 'HILT_OF_TRUE_ICE',
        itemName: 'Hilt of True Ice',
        itemDisplayName: `${LEGENDARY}Hilt of True Ice`,
        npcPrice: 0,
    },
    {
        itemId: 'ENCHANTMENT_PROSPERITY_1',
        itemName: 'Enchanted Book (Prosperity I)',
        itemDisplayName: `${RARE}Prosperity I ${WHITE}Book`,
        npcPrice: 0,
    },
    {
        itemId: 'BABY_YETI;3',
        itemName: '[Lvl 1] Baby Yeti (EPIC)',
        itemDisplayName: `${EPIC}Baby Yeti`,
        npcPrice: 10000,
    },
    {
        itemId: 'BABY_YETI;4',
        itemName: '[Lvl 1] Baby Yeti (LEGENDARY)',
        itemDisplayName: `${LEGENDARY}Baby Yeti`,
        npcPrice: 1000000,
    },

    // Fishing Festival

    {
        itemId: 'NURSE_SHARK_TOOTH',
        itemName: 'Nurse Shark Tooth',
        itemDisplayName: `${UNCOMMON}Nurse Shark Tooth`,
        npcPrice: 0,
    },
    {
        itemId: 'BLUE_SHARK_TOOTH',
        itemName: 'Blue Shark Tooth',
        itemDisplayName: `${RARE}Blue Shark Tooth`,
        npcPrice: 0,
    },
    {
        itemId: 'TIGER_SHARK_TOOTH',
        itemName: 'Tiger Shark Tooth',
        itemDisplayName: `${EPIC}Tiger Shark Tooth`,
        npcPrice: 0,
    },
    {
        itemId: 'GREAT_WHITE_SHARK_TOOTH',
        itemName: 'Great White Shark Tooth',
        itemDisplayName: `${LEGENDARY}Great White Shark Tooth`,
        npcPrice: 0,
    },
    {
        itemId: 'SHARK_FIN',
        itemName: 'Shark Fin',
        itemDisplayName: `${RARE}Shark Fin`,
        npcPrice: 0,
    },
    {
        itemId: 'MEGALODON;3',
        itemName: '[Lvl 1] Megalodon (EPIC)',
        itemDisplayName: `${EPIC}Megalodon`,
        npcPrice: 500000,
    },
    {
        itemId: 'MEGALODON;4',
        itemName: '[Lvl 1] Megalodon (LEGENDARY)',
        itemDisplayName: `${LEGENDARY}Megalodon`,
        npcPrice: 2500000,
    },

    // Runes

    {
        itemId: 'TIDAL_RUNE;1',
        itemName: '◆ Tidal Rune I',
        itemDisplayName: `${LEGENDARY}Tidal Rune I`,
        npcPrice: 1,
    },
    {
        itemId: 'MUSIC_RUNE;1',
        itemName: '◆ Music Rune I',
        itemDisplayName: `${EPIC}Music Rune I`,
        npcPrice: 1,
    },

    // Trophy

    {
        itemId: 'OBFUSCATED_FISH_1_BRONZE',
        itemName: 'Obfuscated 1 BRONZE',
        itemDisplayName: `${COMMON}${OBFUSCATED}Obfuscated 1 ${DARK_GRAY}${BOLD}BRONZE`,
        npcPrice: 0,
        amountOfMagmaFish: 16,
    },
    {
        itemId: 'OBFUSCATED_FISH_1_SILVER',
        itemName: 'Obfuscated 1 SILVER',
        itemDisplayName: `${COMMON}${OBFUSCATED}Obfuscated 1 ${GRAY}${BOLD}SILVER`,
        npcPrice: 0,
        amountOfMagmaFish: 24,
    },
    {
        itemId: 'OBFUSCATED_FISH_1_GOLD',
        itemName: 'Obfuscated 1 GOLD',
        itemDisplayName: `${COMMON}${OBFUSCATED}Obfuscated 1 ${GOLD}${BOLD}GOLD`,
        npcPrice: 0,
        amountOfMagmaFish: 32,
    },
    {
        itemId: 'OBFUSCATED_FISH_1_DIAMOND',
        itemName: 'Obfuscated 1 DIAMOND',
        itemDisplayName: `${COMMON}${OBFUSCATED}Obfuscated 1 ${AQUA}${BOLD}DIAMOND`,
        npcPrice: 0,
        amountOfMagmaFish: 48,
    },
    {
        itemId: 'OBFUSCATED_FISH_2_BRONZE',
        itemName: 'Obfuscated 2 BRONZE',
        itemDisplayName: `${UNCOMMON}${OBFUSCATED}Obfuscated 2 ${DARK_GRAY}${BOLD}BRONZE`,
        npcPrice: 0,
        amountOfMagmaFish: 40,
    },
    {
        itemId: 'OBFUSCATED_FISH_2_SILVER',
        itemName: 'Obfuscated 2 SILVER',
        itemDisplayName: `${UNCOMMON}${OBFUSCATED}Obfuscated 2 ${GRAY}${BOLD}SILVER`,
        npcPrice: 0,
        amountOfMagmaFish: 60,
    },
    {
        itemId: 'OBFUSCATED_FISH_2_GOLD',
        itemName: 'Obfuscated 2 GOLD',
        itemDisplayName: `${UNCOMMON}${OBFUSCATED}Obfuscated 2 ${GOLD}${BOLD}GOLD`,
        npcPrice: 0,
        amountOfMagmaFish: 80,
    },
    {
        itemId: 'OBFUSCATED_FISH_2_DIAMOND',
        itemName: 'Obfuscated 2 DIAMOND',
        itemDisplayName: `${UNCOMMON}${OBFUSCATED}Obfuscated 2 ${AQUA}${BOLD}DIAMOND`,
        npcPrice: 0,
        amountOfMagmaFish: 120,
    },
    {
        itemId: 'OBFUSCATED_FISH_3_BRONZE',
        itemName: 'Obfuscated 3 BRONZE',
        itemDisplayName: `${RARE}${OBFUSCATED}Obfuscated 3 ${DARK_GRAY}${BOLD}BRONZE`,
        npcPrice: 0,
        amountOfMagmaFish: 400,
    },
    {
        itemId: 'OBFUSCATED_FISH_3_SILVER',
        itemName: 'Obfuscated 3 SILVER',
        itemDisplayName: `${RARE}${OBFUSCATED}Obfuscated 3 ${GRAY}${BOLD}SILVER`,
        npcPrice: 0,
        amountOfMagmaFish: 700,
    },
    {
        itemId: 'OBFUSCATED_FISH_3_GOLD',
        itemName: 'Obfuscated 3 GOLD',
        itemDisplayName: `${RARE}${OBFUSCATED}Obfuscated 3 ${GOLD}${BOLD}GOLD`,
        npcPrice: 0,
        amountOfMagmaFish: 1000,
    },
    {
        itemId: 'OBFUSCATED_FISH_3_DIAMOND',
        itemName: 'Obfuscated 3 DIAMOND',
        itemDisplayName: `${RARE}${OBFUSCATED}Obfuscated 3 ${AQUA}${BOLD}DIAMOND`,
        npcPrice: 0,
        amountOfMagmaFish: 1300,
    },
    {
        itemId: 'BLOBFISH_BRONZE',
        itemName: 'Blobfish BRONZE',
        itemDisplayName: `${COMMON}${OBFUSCATED}Blobfish ${DARK_GRAY}${BOLD}BRONZE`,
        npcPrice: 0,
        amountOfMagmaFish: 4,
    },
    {
        itemId: 'BLOBFISH_SILVER',
        itemName: 'Blobfish SILVER',
        itemDisplayName: `${COMMON}${OBFUSCATED}Blobfish ${GRAY}${BOLD}SILVER`,
        npcPrice: 0,
        amountOfMagmaFish: 8,
    },
    {
        itemId: 'BLOBFISH_GOLD',
        itemName: 'Blobfish GOLD',
        itemDisplayName: `${COMMON}${OBFUSCATED}Blobfish ${GOLD}${BOLD}GOLD`,
        npcPrice: 0,
        amountOfMagmaFish: 12,
    },
    {
        itemId: 'BLOBFISH_DIAMOND',
        itemName: 'Blobfish DIAMOND',
        itemDisplayName: `${COMMON}${OBFUSCATED}Blobfish ${AQUA}${BOLD}DIAMOND`,
        npcPrice: 0,
        amountOfMagmaFish: 16,
    },


    // Baits and fished from water/lava

    // Dyes
];