import { AQUA, BOLD, COMMON, DARK_GRAY, EPIC, GOLD, GRAY, LEGENDARY, MYTHIC, OBFUSCATED, RARE, RED, SPECIAL, UNCOMMON, WHITE } from "./formatting";

// itemId - ID of the item used by bazaar or auction APIs
// itemName - name without formatting used to understand what item is dropped
// itemAlternateNames - support for item name modifications made by mods
// itemDisplayName - name with formatting
// npcPrice - NPC price if exists, or 0
// shouldAnnounceRareDrop - if the item should be announced as a rare drop in player's chat (for valuable drops which have no standart RARE DROP! message from Hypixel)

export const FISHING_PROFIT_ITEMS = [

    // Dyes

    {
        itemId: 'DYE_TREASURE',
        itemName: 'Treasure Dye',
        itemDisplayName: `${LEGENDARY}${BOLD}Treasure Dye`,
        npcPrice: 0,
    },
    {
        itemId: 'DYE_AQUAMARINE',
        itemName: 'Aquamarine Dye',
        itemDisplayName: `${LEGENDARY}${BOLD}Aquamarine Dye`,
        npcPrice: 0,
    },
    {
        itemId: 'DYE_ICEBERG',
        itemName: 'Iceberg Dye',
        itemDisplayName: `${LEGENDARY}${BOLD}Iceberg Dye`,
        npcPrice: 0,
    },
    {
        itemId: 'DYE_CARMINE',
        itemName: 'Carmine Dye',
        itemDisplayName: `${LEGENDARY}${BOLD}Carmine Dye`,
        npcPrice: 0,
    },
    {
        itemId: 'DYE_MIDNIGHT',
        itemName: 'Midnight Dye',
        itemDisplayName: `${LEGENDARY}${BOLD}Midnight Dye`,
        npcPrice: 0,
    },
    {
        itemId: 'DYE_PERIWINKLE',
        itemName: 'Periwinkle Dye',
        itemDisplayName: `${LEGENDARY}${BOLD}Periwinkle Dye`,
        npcPrice: 0,
    },
    {
        itemId: 'DYE_BONE',
        itemName: 'Bone Dye',
        itemDisplayName: `${LEGENDARY}${BOLD}Bone Dye`,
        npcPrice: 0,
    },

    // Treasures

    {
        itemId: 'TITANIC_EXP_BOTTLE',
        itemName: 'Titanic Experience Bottle',
        itemDisplayName: `${RARE}Titanic Experience Bottle`,
        npcPrice: 5000,
    },
    {
        itemId: 'GRAND_EXP_BOTTLE',
        itemName: 'Grand Experience Bottle',
        itemDisplayName: `${UNCOMMON}Grand Experience Bottle`,
        npcPrice: 480,
    },
    {
        itemId: 'ESSENCE_ICE',
        itemName: 'Ice Essence',
        itemDisplayName: `${UNCOMMON}Ice Essence`,
        npcPrice: 0,
    },
    {
        itemId: 'BOUNCY_BEACH_BALL',
        itemName: 'Bouncy Beach Ball',
        itemDisplayName: `${EPIC}Bouncy Beach Ball`,
        npcPrice: 0,
    },
    {
        itemId: 'GIANT_BOUNCY_BEACH_BALL',
        itemName: 'Giant Bouncy Beach Ball',
        itemDisplayName: `${LEGENDARY}Giant Bouncy Beach Ball`,
        npcPrice: 0,
    },
    {
        itemId: 'WATER_ORB',
        itemName: 'Water Orb',
        itemDisplayName: `${EPIC}Water Orb`,
        npcPrice: 3000,
    },
    {
        itemId: 'PRISMARINE_CRYSTALS',
        itemName: 'Prismarine Crystals',
        itemDisplayName: `${COMMON}Prismarine Crystals`,
        npcPrice: 5,
    },
    {
        itemId: 'PRISMARINE_SHARD',
        itemName: 'Prismarine Shard',
        itemDisplayName: `${COMMON}Prismarine Shard`,
        npcPrice: 5,
    },
    {
        itemId: 'RAW_FISH',
        itemName: 'Raw Fish',
        itemDisplayName: `${COMMON}Raw Fish`,
        npcPrice: 6,
    },
    {
        itemId: 'ENCHANTED_RAW_FISH',
        itemName: 'Enchanted Raw Fish',
        itemDisplayName: `${UNCOMMON}Enchanted Raw Fish`,
        npcPrice: 960,
    },
    {
        itemId: 'RAW_FISH:1',
        itemName: 'Raw Salmon',
        itemDisplayName: `${COMMON}Raw Salmon`,
        npcPrice: 10,
    },
    {
        itemId: 'ENCHANTED_RAW_SALMON',
        itemName: 'Enchanted Raw Salmon',
        itemDisplayName: `${UNCOMMON}Enchanted Raw Salmon`,
        npcPrice: 1600,
    },
    {
        itemId: 'RAW_FISH:2',
        itemName: 'Clownfish',
        itemDisplayName: `${COMMON}Clownfish`,
        npcPrice: 20,
    },
    {
        itemId: 'ENCHANTED_CLOWNFISH',
        itemName: 'Enchanted Clownfish',
        itemDisplayName: `${UNCOMMON}Enchanted Clownfish`,
        npcPrice: 3200,
    },
    {
        itemId: 'RAW_FISH:3',
        itemName: 'Pufferfish',
        itemDisplayName: `${COMMON}Pufferfish`,
        npcPrice: 15,
    },
    {
        itemId: 'ENCHANTED_PUFFERFISH',
        itemName: 'Enchanted Pufferfish',
        itemDisplayName: `${UNCOMMON}Enchanted Pufferfish`,
        npcPrice: 2400,
    },
    {
        itemId: 'SPONGE',
        itemName: 'Sponge',
        itemDisplayName: `${COMMON}Sponge`,
        npcPrice: 50,
    },
    {
        itemId: 'ENCHANTED_SPONGE',
        itemName: 'Enchanted Sponge',
        itemDisplayName: `${UNCOMMON}Enchanted Sponge`,
        npcPrice: 2000,
    },
    {
        itemId: 'ENCHANTED_WET_SPONGE',
        itemName: 'Enchanted Wet Sponge',
        itemDisplayName: `${RARE}Enchanted Wet Sponge`,
        npcPrice: 80000,
    },
    {
        itemId: 'CLAY_BALL',
        itemName: 'Clay',
        itemDisplayName: `${COMMON}Clay`,
        npcPrice: 3,
    },
    {
        itemId: 'ENCHANTED_CLAY_BALL',
        itemName: 'Enchanted Clay',
        itemDisplayName: `${UNCOMMON}Enchanted Clay`,
        npcPrice: 480,
    },
    {
        itemId: 'SQUID;0',
        itemName: '[Lvl 1] Squid (COMMON)',
        itemDisplayName: `${COMMON}Squid`,
        npcPrice: 100,
    },
    {
        itemId: 'SQUID;1',
        itemName: '[Lvl 1] Squid (UNCOMMON)',
        itemDisplayName: `${UNCOMMON}Squid`,
        npcPrice: 500,
    },
    {
        itemId: 'SQUID;2',
        itemName: '[Lvl 1] Squid (RARE)',
        itemDisplayName: `${RARE}Squid`,
        npcPrice: 100000,
    },
    {
        itemId: 'SQUID;3',
        itemName: '[Lvl 1] Squid (EPIC)',
        itemDisplayName: `${EPIC}Squid`,
        npcPrice: 200000,
    },
    {
        itemId: 'SQUID;4',
        itemName: '[Lvl 1] Squid (LEGENDARY)',
        itemDisplayName: `${LEGENDARY}Squid`,
        npcPrice: 500000,
    },
    {
        itemId: 'COAL',
        itemName: 'Coal',
        itemDisplayName: `${COMMON}Coal`,
        npcPrice: 2,
    },
    {
        itemId: 'ENCHANTED_COAL',
        itemName: 'Enchanted Coal',
        itemDisplayName: `${UNCOMMON}Enchanted Coal`,
        npcPrice: 320,
    },
    {
        itemId: 'MYCEL',
        itemName: 'Mycelium',
        itemDisplayName: `${COMMON}Mycelium`,
        npcPrice: 5,
    },
    {
        itemId: 'ENCHANTED_MYCELIUM',
        itemName: 'Enchanted Mycelium',
        itemDisplayName: `${UNCOMMON}Enchanted Mycelium`,
        npcPrice: 800,
    },
    {
        itemId: 'SAND:1',
        itemName: 'Red Sand',
        itemDisplayName: `${COMMON}Red Sand`,
        npcPrice: 5,
    },
    {
        itemId: 'ENCHANTED_RED_SAND',
        itemName: 'Enchanted Red Sand',
        itemDisplayName: `${UNCOMMON}Enchanted Red Sand`,
        npcPrice: 800,
    },
    {
        itemId: 'GLOWSTONE_DUST',
        itemName: 'Glowstone Dust',
        itemDisplayName: `${COMMON}Glowstone Dust`,
        npcPrice: 2,
    },
    {
        itemId: 'ENCHANTED_GLOWSTONE_DUST',
        itemName: 'Enchanted Glowstone Dust',
        itemDisplayName: `${UNCOMMON}Enchanted Glowstone Dust`,
        npcPrice: 320,
    },
    {
        itemId: 'QUARTZ',
        itemName: 'Nether Quartz',
        itemDisplayName: `${COMMON}Nether Quartz`,
        npcPrice: 4,
    },
    {
        itemId: 'ENCHANTED_QUARTZ',
        itemName: 'Enchanted Quartz',
        itemDisplayName: `${UNCOMMON}Enchanted Quartz`,
        npcPrice: 640,
    },
    {
        itemId: 'BLAZE_ROD',
        itemName: 'Blaze Rod',
        itemDisplayName: `${COMMON}Blaze Rod`,
        npcPrice: 9,
    },
    {
        itemId: 'ENCHANTED_BLAZE_ROD',
        itemName: 'Enchanted Blaze Rod',
        itemDisplayName: `${UNCOMMON}Enchanted Blaze Rod`,
        npcPrice: 230400,
    },
    {
        itemId: 'ENCHANTED_NETHER_STALK',
        itemName: 'Enchanted Nether Wart',
        itemDisplayName: `${UNCOMMON}Enchanted Nether Wart`,
        npcPrice: 640,
    },
    {
        itemId: 'SULPHUR_ORE',
        itemName: 'Sulphur',
        itemDisplayName: `${UNCOMMON}Sulphur`,
        npcPrice: 10,
    },
    {
        itemId: 'ENCHANTED_SULPHUR',
        itemName: 'Enchanted Sulphur',
        itemDisplayName: `${RARE}Enchanted Sulphur`,
        npcPrice: 1600,
    },
    {
        itemId: 'BLAZE_POWDER',
        itemName: 'Blaze Powder',
        itemDisplayName: `${COMMON}Blaze Powder`,
        npcPrice: 4,
    },
    {
        itemId: 'ENCHANTED_BLAZE_POWDER',
        itemName: 'Enchanted Blaze Powder',
        itemDisplayName: `${UNCOMMON}Enchanted Blaze Powder`,
        npcPrice: 1440,
    },
    {
        itemId: 'NETHERRACK',
        itemName: 'Netherrack',
        itemDisplayName: `${COMMON}Netherrack`,
        npcPrice: 1,
    },
    {
        itemId: 'MAGMA_CREAM',
        itemName: 'Magma Cream',
        itemDisplayName: `${COMMON}Magma Cream`,
        npcPrice: 8,
    },
    {
        itemId: 'ENCHANTED_MAGMA_CREAM',
        itemName: 'Enchanted Magma Cream',
        itemDisplayName: `${UNCOMMON}Enchanted Magma Cream`,
        npcPrice: 1280,
    },
    {
        itemId: 'WHIPPED_MAGMA_CREAM',
        itemName: 'Whipped Magma Cream',
        itemDisplayName: `${RARE}Whipped Magma Cream`,
        npcPrice: 204800,
    },
    {
        itemId: 'GAZING_PEARL',
        itemName: 'Gazing Pearl',
        itemDisplayName: `${RARE}Gazing Pearl`,
        npcPrice: 200,
    },
    {
        itemId: 'TENTACLE_MEAT',
        itemName: 'Tentacle Meat',
        itemDisplayName: `${RARE}Tentacle Meat`,
        npcPrice: 200,
    },
    {
        itemId: 'REKINDLED_EMBER_FRAGMENT',
        itemName: 'Rekindled Ember Fragment',
        itemDisplayName: `${EPIC}Rekindled Ember Fragment`,
        npcPrice: 0,
    },
    {
        itemId: 'SPELL_POWDER',
        itemName: 'Spell Powder',
        itemDisplayName: `${EPIC}Spell Powder`,
        npcPrice: 500,
    },
    {
        itemId: 'LUMINO_FIBER',
        itemName: 'Lumino Fiber',
        itemDisplayName: `${EPIC}Lumino Fiber`,
        npcPrice: 500,
    },
    {
        itemId: 'LEATHER_CLOTH',
        itemName: 'Leather Cloth',
        itemDisplayName: `${EPIC}Leather Cloth`,
        npcPrice: 500,
    },
    {
        itemId: 'HALLOWED_SKULL',
        itemName: 'Hallowed Skull',
        itemDisplayName: `${EPIC}Hallowed Skull`,
        npcPrice: 500,
    },
    {
        itemId: 'CORRUPTED_FRAGMENT',
        itemName: 'Corrupted Fragment',
        itemDisplayName: `${EPIC}Corrupted Fragment`,
        npcPrice: 20,
    },
    {
        itemId: 'FLAMES',
        itemName: 'Flames',
        itemDisplayName: `${RARE}Flames`,
        npcPrice: 200,
    },
    {
        itemId: 'BLAZE_ASHES',
        itemName: 'Blaze Ashes',
        itemDisplayName: `${UNCOMMON}Blaze Ashes`,
        npcPrice: 50,
    },
    {
        itemId: 'BURNING_EYE',
        itemName: 'Burning Eye',
        itemDisplayName: `${UNCOMMON}Burning Eye`,
        npcPrice: 1000,
    },
    {
        itemId: 'MUTATED_BLAZE_ASHES',
        itemName: 'Mutated Blaze Ashes',
        itemDisplayName: `${RARE}Mutated Blaze Ashes`,
        npcPrice: 200,
    },
    {
        itemId: 'WITHER_SOUL',
        itemName: 'Wither Soul',
        itemDisplayName: `${UNCOMMON}Wither Soul`,
        npcPrice: 50,
    },
    {
        itemId: 'MAGMA_CHUNK',
        itemName: 'Magma Chunk',
        itemDisplayName: `${UNCOMMON}Magma Chunk`,
        npcPrice: 50,
    },
    {
        itemId: 'SPECTRE_DUST',
        itemName: 'Spectre Dust',
        itemDisplayName: `${UNCOMMON}Spectre Dust`,
        npcPrice: 50,
    },
    {
        itemId: 'MAGMAG',
        itemName: 'Magmag',
        itemDisplayName: `${UNCOMMON}Magmag`,
        npcPrice: 50,
    },
    {
        itemId: 'BEZOS',
        itemName: 'Bezos',
        itemDisplayName: `${RARE}Bezos`,
        npcPrice: 200,
    },
    {
        itemId: 'DIGESTED_MUSHROOMS',
        itemName: 'Digested Mushrooms',
        itemDisplayName: `${UNCOMMON}Digested Mushrooms`,
        npcPrice: 50,
    },
    {
        itemId: 'HEAVY_PEARL',
        itemName: 'Heavy Pearl',
        itemDisplayName: `${LEGENDARY}Heavy Pearl`,
        npcPrice: 0,
    },
    {
        itemId: 'KADA_LEAD',
        itemName: 'Kada Lead',
        itemDisplayName: `${UNCOMMON}Kada Lead`,
        npcPrice: 50,
    },
    {
        itemId: 'KUUDRA_TIER_KEY',
        itemName: 'Kuudra Key',
        itemDisplayName: `${RARE}Kuudra Key`,
        npcPrice: 0,
    },
    {
        itemId: 'KUUDRA_HOT_TIER_KEY',
        itemName: 'Hot Kuudra Key',
        itemDisplayName: `${EPIC}Hot Kuudra Key`,
        npcPrice: 0,
    },
    {
        itemId: 'KUUDRA_BURNING_TIER_KEY',
        itemName: 'Burning Kuudra Key',
        itemDisplayName: `${EPIC}Burning Kuudra Key`,
        npcPrice: 0,
    },
    {
        itemId: 'KUUDRA_FIERY_TIER_KEY',
        itemName: 'Fiery Kuudra Key',
        itemDisplayName: `${EPIC}Fiery Kuudra Key`,
        npcPrice: 0,
    },
    {
        itemId: 'KUUDRA_INFERNAL_TIER_KEY',
        itemName: 'Infernal Kuudra Key',
        itemDisplayName: `${LEGENDARY}Infernal Kuudra Key`,
        npcPrice: 0,
    },
    {
        itemId: 'LAVA_SHELL',
        itemName: 'Lava Shell',
        itemDisplayName: `${EPIC}Lava Shell`,
        npcPrice: 3000,
    },
    {
        itemId: 'LAVA_WATER_ORB',
        itemName: 'Lava Water Orb',
        itemDisplayName: `${LEGENDARY}Lava Water Orb`,
        npcPrice: 5000,
    },
    // Disks are still obtainable with Stereo Pants
    {
        itemId: 'GOLD_RECORD',
        itemName: 'Music Disc - 13',
        itemDisplayName: `${UNCOMMON}Music Disc - 13`,
        npcPrice: 20,
    },
    {
        itemId: 'GREEN_RECORD',
        itemName: 'Music Disc - Cat',
        itemDisplayName: `${UNCOMMON}Music Disc - Cat`,
        npcPrice: 20,
    },
    {
        itemId: 'RECORD_3',
        itemName: 'Music Disc - Blocks',
        itemDisplayName: `${UNCOMMON}Music Disc - Blocks`,
        npcPrice: 20,
    },
    {
        itemId: 'RECORD_4',
        itemName: 'Music Disc - Chirp',
        itemDisplayName: `${UNCOMMON}Music Disc - Chirp`,
        npcPrice: 20,
    },
    {
        itemId: 'RECORD_5',
        itemName: 'Music Disc - Far',
        itemDisplayName: `${UNCOMMON}Music Disc - Far`,
        npcPrice: 20,
    },
    {
        itemId: 'RECORD_6',
        itemName: 'Music Disc - Mall',
        itemDisplayName: `${UNCOMMON}Music Disc - Mall`,
        npcPrice: 20,
    },
    {
        itemId: 'RECORD_7',
        itemName: 'Music Disc - Mellohi',
        itemDisplayName: `${UNCOMMON}Music Disc - Mellohi`,
        npcPrice: 20,
    },
    {
        itemId: 'RECORD_8',
        itemName: 'Music Disc - Stal',
        itemDisplayName: `${UNCOMMON}Music Disc - Stal`,
        npcPrice: 20,
    },
    {
        itemId: 'RECORD_9',
        itemName: 'Music Disc - Strad',
        itemDisplayName: `${UNCOMMON}Music Disc - Strad`,
        npcPrice: 20,
    },
    {
        itemId: 'RECORD_10',
        itemName: 'Music Disc - Ward',
        itemDisplayName: `${UNCOMMON}Music Disc - Ward`,
        npcPrice: 20,
    },
    {
        itemId: 'RECORD_11',
        itemName: 'Music Disc - 11',
        itemDisplayName: `${UNCOMMON}Music Disc - 11`,
        npcPrice: 20,
    },
    {
        itemId: 'RECORD_12',
        itemName: 'Music Disc - Wait',
        itemDisplayName: `${UNCOMMON}Music Disc - Wait`,
        npcPrice: 20,
    },

    // Junk
    {
        itemId: 'RUSTY_COIN',
        itemName: 'Rusty Coin',
        itemDisplayName: `${UNCOMMON}Rusty Coin`,
        npcPrice: 1000,
    },
    {
        itemId: 'BUSTED_BELT_BUCKLE',
        itemName: 'Busted Belt Buckle',
        itemDisplayName: `${RARE}Busted Belt Buckle`,
        npcPrice: 10000,
    },
    {
        itemId: 'OLD_LEATHER_BOOT',
        itemName: 'Old Leather Boot',
        itemDisplayName: `${EPIC}Old Leather Boot`,
        npcPrice: 25000,
    },
    {
        itemId: 'MOBY_DUCK',
        itemName: 'Moby-Duck',
        itemDisplayName: `${RARE}Moby-Duck`,
        npcPrice: 1000000,
    },

    // Water

    {
        itemId: 'CARNIVAL_TICKET',
        itemName: 'Carnival Ticket',
        itemDisplayName: `${UNCOMMON}Carnival Ticket`,
        npcPrice: 0,
    },
    {
        itemId: 'BOBBIN_SCRIPTURES',
        itemName: 'Bobbin\' Scriptures',
        itemDisplayName: `${RARE}Bobbin\' Scriptures`,
        npcPrice: 35000,
        shouldAnnounceRareDrop: true,
    },
    {
        itemId: 'CHUM',
        itemName: 'Chum',
        itemDisplayName: `${UNCOMMON}Chum`,
        npcPrice: 0,
    },
    {
        itemId: 'WATER_LILY',
        itemName: 'Lily Pad',
        itemDisplayName: `${COMMON}Lily Pad`,
        npcPrice: 10,
    },
    {
        itemId: 'ENCHANTED_WATER_LILY',
        itemName: 'Enchanted Lily Pad',
        itemDisplayName: `${UNCOMMON}Enchanted Lily Pad`,
        npcPrice: 1600,
    },
    {
        itemId: 'INK_SACK',
        itemName: 'Ink Sac',
        itemDisplayName: `${COMMON}Ink Sac`,
        npcPrice: 2,
    },
    {
        itemId: 'ENCHANTED_PRISMARINE_CRYSTALS',
        itemName: 'Enchanted Prismarine Crystals',
        itemDisplayName: `${UNCOMMON}Enchanted Prismarine Crystals`,
        npcPrice: 400,
    },
    {
        itemId: 'ENCHANTED_PRISMARINE_SHARD',
        itemName: 'Enchanted Prismarine Shard',
        itemDisplayName: `${UNCOMMON}Enchanted Prismarine Shard`,
        npcPrice: 400,
    },
    {
        itemId: 'BONE',
        itemName: 'Bone',
        itemDisplayName: `${COMMON}Bone`,
        npcPrice: 2,
    },
    {
        itemId: 'ENCHANTED_BONE',
        itemName: 'Enchanted Bone',
        itemDisplayName: `${UNCOMMON}Enchanted Bone`,
        npcPrice: 320,
    },
    {
        itemId: 'SEA_LANTERN',
        itemName: 'Sea Lantern',
        itemDisplayName: `${COMMON}Sea Lantern`,
        npcPrice: 45,
    },
    {
        itemId: 'ROTTEN_FLESH',
        itemName: 'Rotten Flesh',
        itemDisplayName: `${COMMON}Rotten Flesh`,
        npcPrice: 2,
    },
    {
        itemId: 'ENCHANTED_ROTTEN_FLESH',
        itemName: 'Enchanted Rotten Flesh',
        itemDisplayName: `${UNCOMMON}Enchanted Rotten Flesh`,
        npcPrice: 320,
    },
    {
        itemId: 'ENCHANTED_FEATHER',
        itemName: 'Enchanted Feather',
        itemDisplayName: `${UNCOMMON}Enchanted Feather`,
        npcPrice: 480,
    },
    {
        itemId: 'ENCHANTED_IRON',
        itemName: 'Enchanted Iron',
        itemDisplayName: `${UNCOMMON}Enchanted Iron`,
        npcPrice: 480,
    },
    {
        itemId: 'GOLD_INGOT',
        itemName: 'Gold Ingot',
        itemDisplayName: `${COMMON}Gold Ingot`,
        npcPrice: 4,
    },
    {
        itemId: 'ENCHANTED_GOLD',
        itemName: 'Enchanted Gold',
        itemDisplayName: `${UNCOMMON}Enchanted Gold`,
        npcPrice: 640,
    },
    {
        itemId: 'ENCHANTED_DIAMOND',
        itemName: 'Enchanted Diamond',
        itemDisplayName: `${UNCOMMON}Enchanted Diamond`,
        npcPrice: 1280,
    },
    {
        itemId: 'RED_MUSHROOM',
        itemName: 'Red Mushroom',
        itemDisplayName: `${COMMON}Red Mushroom`,
        npcPrice: 10,
    },
    {
        itemId: 'FAIRY_HELMET',
        itemName: 'Fairy\'s Fedora',
        itemDisplayName: `${RARE}Fairy's Fedora`,
        npcPrice: 420,
    },
    {
        itemId: 'FAIRY_CHESTPLATE',
        itemName: 'Fairy\'s Polo',
        itemDisplayName: `${RARE}Fairy's Polo`,
        npcPrice: 420,
    },
    {
        itemId: 'FAIRY_LEGGINGS',
        itemName: 'Fairy\'s Trousers',
        itemDisplayName: `${RARE}Fairy's Trousers`,
        npcPrice: 420,
    },
    {
        itemId: 'FAIRY_BOOTS',
        itemName: 'Fairy\'s Galoshes',
        itemDisplayName: `${RARE}Fairy's Galoshes`,
        npcPrice: 420,
    },
    {
        itemId: 'SQUID_BOOTS',
        itemName: 'Squid Boots',
        itemDisplayName: `${UNCOMMON}Squid Boots`,
        npcPrice: 15,
    },
    {
        itemId: 'AGARIMOO_TONGUE',
        itemName: 'Agarimoo Tongue',
        itemDisplayName: `${RARE}Agarimoo Tongue`,
        npcPrice: 2050,
    },
    {
        itemId: 'ENCHANTMENT_CORRUPTION_1',
        itemName: 'Enchanted Book (Corruption I)',
        itemDisplayName: `${RARE}Corruption I ${WHITE}Book`,
        npcPrice: 0,
    },
    {
        itemId: 'ENCHANTMENT_MAGNET_6',
        itemName: 'Enchanted Book (Magnet VI)',
        itemAlternateNames: [ 'Enchanted Book (Magnet 6)' ],
        itemDisplayName: `${RARE}Magnet VI ${WHITE}Book`,
        npcPrice: 0,
    },
    {
        itemId: 'ENCHANTMENT_FRAIL_6',
        itemName: 'Enchanted Book (Frail VI)',
        itemAlternateNames: [ 'Enchanted Book (Frail 6)' ],
        itemDisplayName: `${RARE}Frail VI ${WHITE}Book`,
        npcPrice: 0,
    },
    {
        itemId: 'ENCHANTMENT_LURE_6',
        itemName: 'Enchanted Book (Lure VI)',
        itemAlternateNames: [ 'Enchanted Book (Lure 6)' ],
        itemDisplayName: `${RARE}Lure VI ${WHITE}Book`,
        npcPrice: 0,
    },
    {
        itemId: 'ENCHANTMENT_ANGLER_6',
        itemName: 'Enchanted Book (Angler VI)',
        itemAlternateNames: [ 'Enchanted Book (Angler 6)' ],
        itemDisplayName: `${RARE}Angler VI ${WHITE}Book`,
        npcPrice: 0,
    },
    {
        itemId: 'ENCHANTMENT_SPIKED_HOOK_6',
        itemName: 'Enchanted Book (Spiked Hook VI)',
        itemAlternateNames: [ 'Enchanted Book (Spiked Hook 6)' ],
        itemDisplayName: `${RARE}Spiked Hook VI ${WHITE}Book`,
        npcPrice: 0,
    },
    {
        itemId: 'ENCHANTMENT_LUCK_OF_THE_SEA_6',
        itemName: 'Enchanted Book (Luck of the Sea VI)',
        itemAlternateNames: [ 'Enchanted Book (Luck of the Sea 6)' ],
        itemDisplayName: `${RARE}Luck of the Sea VI ${WHITE}Book`,
        npcPrice: 0,
        shouldAnnounceRareDrop: true,
    },
    {
        itemId: 'ENCHANTMENT_CASTER_6',
        itemName: 'Enchanted Book (Caster VI)',
        itemAlternateNames: [ 'Enchanted Book (Caster 6)' ],
        itemDisplayName: `${RARE}Caster VI ${WHITE}Book`,
        npcPrice: 0,
    },
    {
        itemId: 'ENCHANTMENT_BLESSING_6',
        itemName: 'Enchanted Book (Blessing VI)',
        itemAlternateNames: [ 'Enchanted Book (Blessing 6)' ],
        itemDisplayName: `${RARE}Blessing VI ${WHITE}Book`,
        npcPrice: 0,
        shouldAnnounceRareDrop: true,
    },
    {
        itemId: 'CARROT_ITEM',
        itemName: 'Carrot',
        itemDisplayName: `${COMMON}Carrot`,
        npcPrice: 3,
    },
    {
        itemId: 'ENCHANTED_CARROT',
        itemName: 'Enchanted Carrot',
        itemDisplayName: `${UNCOMMON}Enchanted Carrot`,
        npcPrice: 480,
    },
    {
        itemId: 'WOOL',
        itemName: 'White Wool',
        itemDisplayName: `${COMMON}White Wool`,
        npcPrice: 2,
    },
    {
        itemId: 'MUTTON',
        itemName: 'Mutton',
        itemDisplayName: `${COMMON}Mutton`,
        npcPrice: 5,
    },
    {
        itemId: 'ENCHANTED_MUTTON',
        itemName: 'Enchanted Mutton',
        itemDisplayName: `${UNCOMMON}Enchanted Mutton`,
        npcPrice: 800,
    },
    {
        itemId: 'ENCHANTED_COOKED_MUTTON',
        itemName: 'Enchanted Cooked Mutton',
        itemDisplayName: `${RARE}Enchanted Cooked Mutton`,
        npcPrice: 128000,
    },
    {
        itemId: 'RABBIT',
        itemName: 'Raw Rabbit',
        itemDisplayName: `${COMMON}Raw Rabbit`,
        npcPrice: 4,
    },
    {
        itemId: 'ENCHANTED_RABBIT',
        itemName: 'Enchanted Raw Rabbit',
        itemDisplayName: `${UNCOMMON}Enchanted Raw Rabbit`,
        npcPrice: 640,
    },
    {
        itemId: 'RABBIT_HIDE',
        itemName: 'Rabbit Hide',
        itemDisplayName: `${COMMON}Rabbit Hide`,
        npcPrice: 5,
    },
    {
        itemId: 'RABBIT_FOOT',
        itemName: 'Rabbit\'s Foot',
        itemDisplayName: `${COMMON}Rabbit's Foot`,
        npcPrice: 5,
    },
    {
        itemId: 'ENCHANTED_RABBIT_FOOT',
        itemName: 'Enchanted Rabbit Foot',
        itemDisplayName: `${UNCOMMON}Enchanted Rabbit Foot`,
        npcPrice: 800,
    },
    {
        itemId: 'RABBIT_HAT',
        itemName: 'Rabbit Hat',
        itemDisplayName: `${UNCOMMON}Rabbit Hat`,
        npcPrice: 10,
    },
    {
        itemId: 'PET_ITEM_LUCKY_CLOVER_DROP',
        itemName: 'Lucky Clover Core',
        itemDisplayName: `${EPIC}Lucky Clover Core`,
        npcPrice: 0,
    },
    {
        itemId: 'PET_ITEM_FISHING_SKILL_BOOST_UNCOMMON',
        itemName: 'Fishing Exp Boost (UNCOMMON)',
        itemDisplayName: `${UNCOMMON}Fishing Exp Boost +30%`,
        npcPrice: 0,
    },
    {
        itemId: 'PET_ITEM_FISHING_SKILL_BOOST_RARE',
        itemName: 'Fishing Exp Boost (RARE)',
        itemDisplayName: `${RARE}Fishing Exp Boost +40%`,
        npcPrice: 0,
        shouldAnnounceRareDrop: true,
    },
    {
        itemId: 'PET_ITEM_FISHING_SKILL_BOOST_EPIC',
        itemName: 'Fishing Exp Boost (EPIC)',
        itemDisplayName: `${EPIC}Fishing Exp Boost +50%`,
        npcPrice: 0,
        shouldAnnounceRareDrop: true,
    },
    {
        itemId: 'WATER_HYDRA_HEAD',
        itemName: 'Water Hydra Head',
        itemDisplayName: `${EPIC}Water Hydra Head`,
        npcPrice: 500,
        shouldAnnounceRareDrop: true,
    },
    {
        itemId: 'FISH_AFFINITY_TALISMAN',
        itemName: 'Fish Affinity Talisman',
        itemDisplayName: `${RARE}Fish Affinity Talisman`,
        npcPrice: 1000,
        shouldAnnounceRareDrop: true,
    },
    {
        itemId: 'DIVER_FRAGMENT',
        itemName: 'Emperor\'s Skull',
        itemDisplayName: `${RARE}Emperor's Skull`,
        npcPrice: 100,
        shouldAnnounceRareDrop: true,
    },
    {
        itemId: 'SHREDDED_LINE',
        itemName: 'Shredded Line',
        itemDisplayName: `${RARE}Shredded Line`,
        npcPrice: 250000,
    },
    {
        itemId: 'FLYING_FISH;2',
        itemName: '[Lvl 1] Flying Fish (RARE)',
        itemDisplayName: `${RARE}Flying Fish`,
        npcPrice: 0,
    },
    {
        itemId: 'FLYING_FISH;3',
        itemName: '[Lvl 1] Flying Fish (EPIC)',
        itemDisplayName: `${EPIC}Flying Fish`,
        npcPrice: 100000,
    },
    {
        itemId: 'FLYING_FISH;4',
        itemName: '[Lvl 1] Flying Fish (LEGENDARY)',
        itemDisplayName: `${LEGENDARY}Flying Fish`,
        npcPrice: 250000,
    },

    // Bayou

    {
        itemId: 'HALF_EATEN_MUSHROOM',
        itemName: 'Half-Eaten Mushroom',
        itemDisplayName: `${UNCOMMON}Half-Eaten Mushroom`,
        npcPrice: 500,
    },
    {
        itemId: 'BROKEN_RADAR',
        itemName: 'Broken Radar',
        itemDisplayName: `${RARE}Broken Radar`,
        npcPrice: 25000,
    },
    {
        itemId: 'EDIBLE_SEAWEED',
        itemName: 'Edible Seaweed',
        itemDisplayName: `${RARE}Edible Seaweed`,
        npcPrice: 50000,
    },
    {
        itemId: 'BLUE_RING',
        itemName: 'Blue Ring',
        itemDisplayName: `${RARE}Blue Ring`,
        npcPrice: 25000,
    },
    {
        itemId: 'OCTOPUS_TENDRIL',
        itemName: 'Octopus Tendril',
        itemDisplayName: `${LEGENDARY}Octopus Tendril`,
        npcPrice: 1000000,
    },
    {
        itemId: 'ENCHANTED_JUNGLE_LOG',
        itemName: 'Enchanted Jungle Wood',
        itemDisplayName: `${UNCOMMON}Enchanted Jungle Wood`,
        npcPrice: 320,
    },
    {
        itemId: 'TIKI_MASK',
        itemName: 'Tiki Mask',
        itemDisplayName: `${LEGENDARY}Tiki Mask`,
        npcPrice: 1000000,
    },
    {
        itemId: 'TROUBLED_BUBBLE',
        itemName: 'Troubled Bubble',
        itemDisplayName: `${LEGENDARY}Troubled Bubble`,
        npcPrice: 1000000,
    },
    {
        itemId: 'CAN_OF_WORMS',
        itemName: 'Can of Worms',
        itemDisplayName: `${UNCOMMON}Can of Worms`,
        npcPrice: 500,
    },
    {
        itemId: 'BRONZE_BOWL',
        itemName: 'Bronze Bowl',
        itemDisplayName: `${UNCOMMON}Bronze Bowl`,
        npcPrice: 5000,
    },
    {
        itemId: 'OVERFLOWING_TRASH_CAN',
        itemName: 'Overflowing Trash Can',
        itemDisplayName: `${UNCOMMON}Overflowing Trash Can`,
        npcPrice: 10000,
    },
    {
        itemId: 'TORN_CLOTH',
        itemName: 'Torn Cloth',
        itemDisplayName: `${UNCOMMON}Torn Cloth`,
        npcPrice: 5000,
    },
    {
        itemId: 'CALCIFIED_HEART',
        itemName: 'Calcified Heart',
        itemDisplayName: `${RARE}Calcified Heart`,
        npcPrice: 5000,
    },
    {
        itemId: 'ENCHANTMENT_RESPITE_1',
        itemName: 'Enchanted Book (Respite I)',
        itemAlternateNames: [ 'Enchanted Book (Respite 1)' ],
        itemDisplayName: `${RARE}Respite I ${WHITE}Book`,
        npcPrice: 0,
    },
    {
        itemId: 'SLIME_BALL',
        itemName: 'Slimeball',
        itemDisplayName: `${COMMON}Slimeball`,
        npcPrice: 5,
    },
    {
        itemId: 'ENCHANTED_SLIME_BALL',
        itemName: 'Enchanted Slimeball',
        itemDisplayName: `${UNCOMMON}Enchanted Slimeball`,
        npcPrice: 800,
    },
    {
        itemId: 'ENCHANTED_SLIME_BLOCK',
        itemName: 'Enchanted Slime Block',
        itemDisplayName: `${RARE}Enchanted Slime Block`,
        npcPrice: 128000,
    },
    {
        itemId: 'POISON_SAMPLE',
        itemName: 'Poison Sample',
        itemDisplayName: `${UNCOMMON}Poison Sample`,
        npcPrice: 500,
    },
    {
        itemId: 'ALLIGATOR_SKIN',
        itemName: 'Alligator Skin',
        itemDisplayName: `${EPIC}Alligator Skin`,
        npcPrice: 5000,
    },
    {
        itemId: 'TITANOBOA_SHED',
        itemName: 'Titanoboa Shed',
        itemDisplayName: `${LEGENDARY}Titanoboa Shed`,
        npcPrice: 500000,
    },
    {
        itemId: 'ENCHANTED_CLAY_BLOCK',
        itemName: 'Enchanted Clay Block',
        itemDisplayName: `${RARE}Enchanted Clay Block`,
        npcPrice: 76800,
    },

    // Crimson Isle

    {
        itemId: 'RAW_CHICKEN',
        itemName: 'Raw Chicken',
        itemDisplayName: `${COMMON}Raw Chicken`,
        npcPrice: 4,
    },
    {
        itemId: 'ENCHANTED_RAW_CHICKEN',
        itemName: 'Enchanted Raw Chicken',
        itemDisplayName: `${UNCOMMON}Enchanted Raw Chicken`,
        npcPrice: 640,
    },
    {
        itemId: 'FRIED_FEATHER',
        itemName: 'Fried Feather',
        itemDisplayName: `${UNCOMMON}Fried Feather`,
        npcPrice: 10000,
    },
    {
        itemId: 'SINGED_POWDER',
        itemName: 'Singed Powder',
        itemDisplayName: `${UNCOMMON}Singed Powder`,
        npcPrice: 1000,
    },
    {
        itemId: 'ENCHANTMENT_FIRE_PROTECTION_6',
        itemName: 'Enchanted Book (Fire Protection VI)',
        itemAlternateNames: [ 'Enchanted Book (Fire Protection 6)' ],
        itemDisplayName: `${RARE}Fire Protection VI ${WHITE}Book`,
        npcPrice: 0,
    },
    {
        itemId: 'SCORCHED_CRAB_STICK',
        itemName: 'Scorched Crab Stick',
        itemDisplayName: `${RARE}Scorched Crab Stick`,
        npcPrice: 25000,
    },
    {
        itemId: 'SCUTTLER_SHELL',
        itemName: 'Scuttler Shell',
        itemDisplayName: `${LEGENDARY}Scuttler Shell`,
        npcPrice: 1000000,
    },
    {
        itemId: 'BRIMSTONE_HANDLE',
        itemName: 'Brimstone Handle',
        itemDisplayName: `${EPIC}Brimstone Handle`,
        npcPrice: 25000,
    },
    {
        itemId: 'BURNT_TEXTS',
        itemName: 'Burnt Texts',
        itemDisplayName: `${LEGENDARY}Burnt Texts`,
        npcPrice: 1000000,
    },
    {
        itemId: 'CHAIN_END_TIMES',
        itemName: 'Chain of the End Times',
        itemDisplayName: `${LEGENDARY}Chain of the End Times`,
        npcPrice: 1000000,
    },
    {
        itemId: 'LUMP_OF_MAGMA',
        itemName: 'Lump of Magma',
        itemDisplayName: `${UNCOMMON}Lump of Magma`,
        npcPrice: 50,
    },
    {
        itemId: 'MOOGMA_PELT',
        itemName: 'Moogma Pelt',
        itemDisplayName: `${UNCOMMON}Moogma Pelt`,
        npcPrice: 50,
    },
    {
        itemId: 'CUP_OF_BLOOD',
        itemName: 'Cup of Blood',
        itemDisplayName: `${UNCOMMON}Cup of Blood`,
        npcPrice: 200,
    },
    {
        itemId: 'PYROCLASTIC_SCALE',
        itemName: 'Pyroclastic Scale',
        itemDisplayName: `${UNCOMMON}Pyroclastic Scale`,
        npcPrice: 50,
    },
    {
        itemId: 'FLAMING_HEART',
        itemName: 'Flaming Heart',
        itemDisplayName: `${RARE}Flaming Heart`,
        npcPrice: 200,
    },
    {
        itemId: 'ORB_OF_ENERGY',
        itemName: 'Orb of Energy',
        itemDisplayName: `${RARE}Orb of Energy`,
        npcPrice: 200,
    },
    {
        itemId: 'HORN_OF_TAURUS',
        itemName: 'Horn of Taurus',
        itemDisplayName: `${EPIC}Horn of Taurus`,
        npcPrice: 500,
    },
    {
        itemId: 'THUNDER_SHARDS',
        itemName: 'Thunder Shards',
        itemDisplayName: `${EPIC}Thunder Shards`,
        npcPrice: 50000,
    },
    {
        itemId: 'MAGMA_FISH',
        itemName: 'Magmafish',
        itemDisplayName: `${RARE}Magmafish`,
        npcPrice: 20,
    },
    {
        itemId: 'MAGMA_FISH_SILVER',
        itemName: 'Silver Magmafish',
        itemDisplayName: `${EPIC}Silver Magmafish`,
        npcPrice: 1600,
    },
    {
        itemId: 'CORRUPTED_NETHER_STAR',
        itemName: 'Nether Star',
        itemDisplayName: `${UNCOMMON}Nether Star`,
        npcPrice: 10000,
    },
    {
        itemId: 'SLUG_BOOTS',
        itemName: 'Slug Boots',
        itemDisplayName: `${RARE}Slug Boots`,
        npcPrice: 5000,
        salvage: {
            essenceType: 'ESSENCE_CRIMSON',
            essenceCount: 15
        },
    },
    {
        itemId: 'MOOGMA_LEGGINGS',
        itemName: 'Moogma Leggings',
        itemDisplayName: `${RARE}Moogma Leggings`,
        npcPrice: 10000,
        salvage: {
            essenceType: 'ESSENCE_CRIMSON',
            essenceCount: 20
        },
    },
    {
        itemId: 'FLAMING_CHESTPLATE',
        itemName: 'Flaming Chestplate',
        itemDisplayName: `${RARE}Flaming Chestplate`,
        npcPrice: 25000,
        salvage: {
            essenceType: 'ESSENCE_CRIMSON',
            essenceCount: 25
        },
    },
    {
        itemId: 'TAURUS_HELMET',
        itemName: 'Taurus Helmet',
        itemDisplayName: `${RARE}Taurus Helmet`,
        npcPrice: 50000,
        salvage: {
            essenceType: 'ESSENCE_CRIMSON',
            essenceCount: 30
        },
    },
    {
        itemId: 'BLADE_OF_THE_VOLCANO',
        itemName: 'Blade of the Volcano',
        itemDisplayName: `${RARE}Blade of the Volcano`,
        npcPrice: 5000,
        salvage: {
            essenceType: 'ESSENCE_CRIMSON',
            essenceCount: 10
        },
    },
    {
        itemId: 'STAFF_OF_THE_VOLCANO',
        itemName: 'Staff of the Volcano',
        itemDisplayName: `${RARE}Staff of the Volcano`,
        npcPrice: 5000,
        salvage: {
            essenceType: 'ESSENCE_CRIMSON',
            essenceCount: 10
        },
    },
    {
        itemId: 'PITCHIN_KOI',
        itemName: 'Pitchin\' Koi',
        itemDisplayName: `${RARE}Pitchin\' Koi`,
        npcPrice: 22222,
    },
    {
        itemId: 'MAGMA_LORD_FRAGMENT',
        itemName: 'Magma Lord Fragment',
        itemDisplayName: `${LEGENDARY}Magma Lord Fragment`,
        npcPrice: 0,
        shouldAnnounceRareDrop: true,
    },
    {
        itemId: 'RADIOACTIVE_VIAL',
        itemName: 'Radioactive Vial',
        itemDisplayName: `${MYTHIC}${BOLD}Radioactive Vial`,
        npcPrice: 100000,
    },
    {
        itemId: 'THUNDER_IN_A_BOTTLE',
        itemName: 'Thunder in a Bottle',
        itemDisplayName: `${EPIC}Thunder in a Bottle`,
        npcPrice: 5000,
    },
    {
        itemId: 'STORM_IN_A_BOTTLE',
        itemName: 'Storm in a Bottle',
        itemDisplayName: `${EPIC}Storm in a Bottle`,
        npcPrice: 5000,
    },
    {
        itemId: 'HURRICANE_IN_A_BOTTLE',
        itemName: 'Hurricane in a Bottle',
        itemDisplayName: `${LEGENDARY}Hurricane in a Bottle`,
        npcPrice: 5000,
    },
    {
        itemId: 'ENCHANTMENT_CHARM_1',
        itemName: 'Enchanted Book (Charm I)',
        itemDisplayName: `${RARE}Charm I ${WHITE}Book`,
        npcPrice: 0,
    },
    {
        itemId: 'ENCHANTMENT_ULTIMATE_FLASH_1',
        itemName: 'Enchanted Book (Flash I)',
        itemAlternateNames: [ 'Enchanted Book (Flash 1)' ],
        itemDisplayName: `${MYTHIC}Flash I ${WHITE}Book`,
        npcPrice: 0,
        shouldAnnounceRareDrop: true,
    },
    {
        itemId: 'ATTRIBUTE_SHARD+ATTRIBUTE_BLAZING_FORTUNE;1',
        itemName: 'Attribute Shard (Blazing Fortune I)',
        itemAlternateNames: [ 'Attribute Shard (Blazing Fortune 1)' ],
        itemDisplayName: `${AQUA}Blazing Fortune I ${WHITE}Attribute Shard`,
        npcPrice: 0,
        shouldAnnounceRareDrop: true,
    },
    {
        itemId: 'ATTRIBUTE_SHARD+ATTRIBUTE_DOUBLE_HOOK;1',
        itemName: 'Attribute Shard (Double Hook I)',
        itemAlternateNames: [ 'Attribute Shard (Double Hook 1)' ],
        itemDisplayName: `${AQUA}Double Hook I ${WHITE}Attribute Shard`,
        npcPrice: 0,
        shouldAnnounceRareDrop: true,
    },
    {
        itemId: 'ATTRIBUTE_SHARD+ATTRIBUTE_FISHERMAN;1',
        itemName: 'Attribute Shard (Fisherman I)',
        itemAlternateNames: [ 'Attribute Shard (Fisherman 1)' ],
        itemDisplayName: `${AQUA}Fisherman I ${WHITE}Attribute Shard`,
        npcPrice: 0,
        shouldAnnounceRareDrop: true,
    },
    {
        itemId: 'ATTRIBUTE_SHARD+ATTRIBUTE_FISHING_EXPERIENCE;1',
        itemName: 'Attribute Shard (Fishing Experience I)',
        itemAlternateNames: [ 'Attribute Shard (Fishing Experience 1)' ],
        itemDisplayName: `${AQUA}Fishing Experience I ${WHITE}Attribute Shard`,
        npcPrice: 0,
        shouldAnnounceRareDrop: true,
    },
    {
        itemId: 'ATTRIBUTE_SHARD+ATTRIBUTE_FISHING_SPEED;1',
        itemName: 'Attribute Shard (Fishing Speed I)',
        itemAlternateNames: [ 'Attribute Shard (Fishing Speed 1)' ],
        itemDisplayName: `${AQUA}Fishing Speed I ${WHITE}Attribute Shard`,
        npcPrice: 0,
        shouldAnnounceRareDrop: true,
    },
    {
        itemId: 'ATTRIBUTE_SHARD+ATTRIBUTE_HUNTER;1',
        itemName: 'Attribute Shard (Hunter I)',
        itemAlternateNames: [ 'Attribute Shard (Hunter 1)' ],
        itemDisplayName: `${AQUA}Hunter I ${WHITE}Attribute Shard`,
        npcPrice: 0,
        shouldAnnounceRareDrop: true,
    },
    {
        itemId: 'ATTRIBUTE_SHARD+ATTRIBUTE_INFECTION;1',
        itemName: 'Attribute Shard (Infection I)',
        itemAlternateNames: [ 'Attribute Shard (Infection 1)' ],
        itemDisplayName: `${AQUA}Infection I ${WHITE}Attribute Shard`,
        npcPrice: 0,
        shouldAnnounceRareDrop: true,
    },
    {
        itemId: 'ATTRIBUTE_SHARD+ATTRIBUTE_TROPHY_HUNTER;1',
        itemName: 'Attribute Shard (Trophy Hunter I)',
        itemAlternateNames: [ 'Attribute Shard (Trophy Hunter 1)' ],
        itemDisplayName: `${AQUA}Trophy Hunter I ${WHITE}Attribute Shard`,
        npcPrice: 0,
        shouldAnnounceRareDrop: true,
    },

    // Crystal Hollows

    {
        itemId: 'HARD_STONE',
        itemName: 'Hard Stone',
        itemDisplayName: `${RARE}Hard Stone`,
        npcPrice: 1,
    },
    {
        itemId: 'MAGMA_CORE',
        itemName: 'Magma Core',
        itemDisplayName: `${RARE}Magma Core`,
        npcPrice: 0,
    },
    {
        itemId: 'BLAZEN_SPHERE',
        itemName: 'Blazen Sphere',
        itemDisplayName: `${RARE}Blazen Sphere`,
        npcPrice: 0,
    },
    {
        itemId: 'ENCHANTMENT_PISCARY_6',
        itemName: 'Enchanted Book (Piscary VI)',
        itemAlternateNames: [ 'Enchanted Book (Piscary 6)' ],
        itemDisplayName: `${RARE}Piscary VI ${WHITE}Book`,
        npcPrice: 0,
        shouldAnnounceRareDrop: true,
    },
    {
        itemId: 'WORM_MEMBRANE',
        itemName: 'Worm Membrane',
        itemDisplayName: `${UNCOMMON}Worm Membrane`,
        npcPrice: 0,
    },
    {
        itemId: 'ETERNAL_FLAME_RING',
        itemName: 'Eternal Flame Ring',
        itemDisplayName: `${UNCOMMON}Eternal Flame Ring`,
        npcPrice: 0,
    },
    {
        itemId: 'ROUGH_JADE_GEM',
        itemName: '☘ Rough Jade Gemstone',
        itemDisplayName: `${COMMON}Rough Jade Gemstone`,
        npcPrice: 3,
    },
    {
        itemId: 'ROUGH_AMETHYST_GEM',
        itemName: '❈ Rough Amethyst Gemstone',
        itemDisplayName: `${COMMON}Rough Amethyst Gemstone`,
        npcPrice: 3,
    },
    {
        itemId: 'ROUGH_AMBER_GEM',
        itemName: '⸕ Rough Amber Gemstone',
        itemDisplayName: `${COMMON}Rough Amber Gemstone`,
        npcPrice: 3,
    },
    {
        itemId: 'ROUGH_SAPPHIRE_GEM',
        itemName: '✎ Rough Sapphire Gemstone',
        itemDisplayName: `${COMMON}Rough Sapphire Gemstone`,
        npcPrice: 3,
    },
    {
        itemId: 'ROUGH_TOPAZ_GEM',
        itemName: '✧ Rough Topaz Gemstone',
        itemDisplayName: `${COMMON}Rough Topaz Gemstone`,
        npcPrice: 3,
    },
    {
        itemId: 'FLAWED_JADE_GEM',
        itemName: '☘ Flawed Jade Gemstone',
        itemDisplayName: `${UNCOMMON}Flawed Jade Gemstone`,
        npcPrice: 3,
    },
    {
        itemId: 'FLAWED_SAPPHIRE_GEM',
        itemName: '✎ Flawed Sapphire Gemstone',
        itemDisplayName: `${UNCOMMON}Flawed Sapphire Gemstone`,
        npcPrice: 3,
    },
    {
        itemId: 'FLAWED_AMETHYST_GEM',
        itemName: '❈ Flawed Amethyst Gemstone',
        itemDisplayName: `${UNCOMMON}Flawed Amethyst Gemstone`,
        npcPrice: 3,
    },

    // Spooky

    {
        itemId: 'HAY_BLOCK',
        itemName: 'Hay Bale',
        itemDisplayName: `${COMMON}Hay Bale`,
        npcPrice: 24,
    },
    {
        itemId: 'GREEN_CANDY',
        itemName: 'Green Candy',
        itemDisplayName: `${UNCOMMON}Green Candy`,
        npcPrice: 0,
    },
    {
        itemId: 'PURPLE_CANDY',
        itemName: 'Purple Candy',
        itemDisplayName: `${EPIC}Purple Candy`,
        npcPrice: 0,
    },
    {
        itemId: 'LUCKY_HOOF',
        itemName: 'Lucky Hoof',
        itemDisplayName: `${UNCOMMON}Lucky Hoof`,
        npcPrice: 0,
    },
    {
        itemId: 'WEREWOLF_SKIN',
        itemName: 'Werewolf Skin',
        itemDisplayName: `${RARE}Werewolf Skin`,
        npcPrice: 0,
    },
    {
        itemId: 'DEEP_SEA_ORB',
        itemName: 'Deep Sea Orb',
        itemDisplayName: `${EPIC}Deep Sea Orb`,
        npcPrice: 0,
    },
    {
        itemId: 'SOUL_FRAGMENT',
        itemName: 'Soul Fragment',
        itemDisplayName: `${EPIC}Soul Fragment`,
        npcPrice: 0,
        shouldAnnounceRareDrop: true,
    },
    {
        itemId: 'PET_ITEM_VAMPIRE_FANG',
        itemName: 'Vampire Fang',
        itemDisplayName: `${LEGENDARY}Vampire Fang`,
        npcPrice: 0,
    },
    {
        itemId: 'PHANTOM_HOOK',
        itemName: 'Phantom Hook',
        itemDisplayName: `${RARE}Phantom Hook`,
        npcPrice: 250000,
    },

    // Winter

    {
        itemId: 'ICE',
        itemName: 'Ice',
        itemDisplayName: `${COMMON}Ice`,
        npcPrice: 0.5,
    },
    {
        itemId: 'PACKED_ICE',
        itemName: 'Packed Ice',
        itemDisplayName: `${COMMON}Packed Ice`,
        npcPrice: 4.5,
    },
    {
        itemId: 'ENCHANTED_ICE',
        itemName: 'Enchanted Ice',
        itemDisplayName: `${UNCOMMON}Enchanted Ice`,
        npcPrice: 80,
    },
    {
        itemId: 'ENCHANTED_PACKED_ICE',
        itemName: 'Enchanted Packed Ice',
        itemDisplayName: `${RARE}Enchanted Packed Ice`,
        npcPrice: 12800,
    },
    {
        itemId: 'SNOWFLAKE_THE_FISH',
        itemName: 'Flake the Fish',
        itemDisplayName: `${COMMON}Flake the Fish`,
        npcPrice: 0,
    },
    {
        itemId: 'SNOW_BALL',
        itemName: 'Snowball',
        itemDisplayName: `${COMMON}Snowball`,
        npcPrice: 1,
    },
    {
        itemId: 'SNOW_BLOCK',
        itemName: 'Snow Block',
        itemDisplayName: `${COMMON}Snow Block`,
        npcPrice: 4,
    },
    {
        itemId: 'ENCHANTED_SNOW_BLOCK',
        itemName: 'Enchanted Snow Block',
        itemDisplayName: `${UNCOMMON}Enchanted Snow Block`,
        npcPrice: 600,
    },
    {
        itemId: 'WINTER_WATER_ORB',
        itemName: 'Winter Water Orb',
        itemDisplayName: `${UNCOMMON}Winter Water Orb`,
        npcPrice: 5000,
    },
    {
        itemId: 'ICY_SINKER',
        itemName: 'Icy Sinker',
        itemDisplayName: `${RARE}Icy Sinker`,
        npcPrice: 10000,
    },
    {
        itemId: 'WALNUT',
        itemName: 'Walnut',
        itemDisplayName: `${UNCOMMON}Walnut`,
        npcPrice: 200,
    },
    {
        itemId: 'WHITE_GIFT',
        itemName: 'White Gift',
        itemDisplayName: `${COMMON}White Gift`,
        npcPrice: 0,
    },
    {
        itemId: 'GREEN_GIFT',
        itemName: 'Green Gift',
        itemDisplayName: `${UNCOMMON}Green Gift`,
        npcPrice: 0,
    },
    {
        itemId: 'RED_GIFT',
        itemName: 'Red Gift',
        itemDisplayName: `${RED}Red Gift`,
        npcPrice: 0,
    },
    {
        itemId: 'PARTY_GIFT',
        itemName: 'Party Gift',
        itemDisplayName: `${UNCOMMON}Party Gift`,
        npcPrice: 0,
    },
    {
        itemId: 'ICE_HUNK',
        itemName: 'Hunk of Ice',
        itemDisplayName: `${UNCOMMON}Hunk of Ice`,
        npcPrice: 0,
    },
    {
        itemId: 'BLUE_ICE_HUNK',
        itemName: 'Hunk of Blue Ice',
        itemDisplayName: `${RARE}Hunk of Blue Ice`,
        npcPrice: 0,
    },
    {
        itemId: 'HILT_OF_TRUE_ICE',
        itemName: 'Hilt of True Ice',
        itemDisplayName: `${LEGENDARY}Hilt of True Ice`,
        npcPrice: 0,
        shouldAnnounceRareDrop: true,
    },
    {
        itemId: 'ENCHANTMENT_PROSPERITY_1',
        itemName: 'Enchanted Book (Prosperity I)',
        itemAlternateNames: [ 'Enchanted Book (Prosperity 1)' ],
        itemDisplayName: `${RARE}Prosperity I ${WHITE}Book`,
        npcPrice: 0,
        shouldAnnounceRareDrop: true,
    },
    {
        itemId: 'BABY_YETI;3',
        itemName: '[Lvl 1] Baby Yeti (EPIC)',
        itemDisplayName: `${EPIC}Baby Yeti`,
        npcPrice: 10000,
    },
    {
        itemId: 'BABY_YETI;4',
        itemName: '[Lvl 1] Baby Yeti (LEGENDARY)',
        itemDisplayName: `${LEGENDARY}Baby Yeti`,
        npcPrice: 1000000,
    },

    // Fishing Festival

    {
        itemId: 'NURSE_SHARK_TOOTH',
        itemName: 'Nurse Shark Tooth',
        itemDisplayName: `${UNCOMMON}Nurse Shark Tooth`,
        npcPrice: 0,
    },
    {
        itemId: 'BLUE_SHARK_TOOTH',
        itemName: 'Blue Shark Tooth',
        itemDisplayName: `${RARE}Blue Shark Tooth`,
        npcPrice: 0,
    },
    {
        itemId: 'TIGER_SHARK_TOOTH',
        itemName: 'Tiger Shark Tooth',
        itemDisplayName: `${EPIC}Tiger Shark Tooth`,
        npcPrice: 0,
    },
    {
        itemId: 'GREAT_WHITE_SHARK_TOOTH',
        itemName: 'Great White Shark Tooth',
        itemDisplayName: `${LEGENDARY}Great White Shark Tooth`,
        npcPrice: 0,
        shouldAnnounceRareDrop: true,
    },
    {
        itemId: 'SHARK_FIN',
        itemName: 'Shark Fin',
        itemDisplayName: `${RARE}Shark Fin`,
        npcPrice: 0,
    },
    {
        itemId: 'MEGALODON;3',
        itemName: '[Lvl 1] Megalodon (EPIC)',
        itemDisplayName: `${EPIC}Megalodon`,
        npcPrice: 500000,
    },
    {
        itemId: 'MEGALODON;4',
        itemName: '[Lvl 1] Megalodon (LEGENDARY)',
        itemDisplayName: `${LEGENDARY}Megalodon`,
        npcPrice: 2500000,
    },

    // The Abandoned Quarry

    {
        itemId: 'MITHRIL_ORE',
        itemName: 'Mithril',
        itemDisplayName: `${COMMON}Mithril`,
        npcPrice: 8,
    },
    {
        itemId: 'ENCHANTED_MITHRIL',
        itemName: 'Enchanted Mithril',
        itemDisplayName: `${RARE}Enchanted Mithril`,
        npcPrice: 1280,
    },
    {
        itemId: 'SPECKLED_TEACUP',
        itemName: 'Speckled Teacup',
        itemDisplayName: `${SPECIAL}Speckled Teacup`,
        npcPrice: 100000,
    },

    // Runes

    {
        itemId: 'TIDAL_RUNE;1',
        itemName: '◆ Tidal Rune I',
        itemAlternateNames: [ '◆ Tidal Rune 1' ],
        itemDisplayName: `${LEGENDARY}Tidal Rune I`,
        npcPrice: 1,
    },
    {
        itemId: 'MUSIC_RUNE;1',
        itemName: '◆ Music Rune I',
        itemAlternateNames: [ '◆ Music Rune 1' ],
        itemDisplayName: `${EPIC}Music Rune I`,
        npcPrice: 1,
    },

    // Trophy

    {
        itemId: 'OBFUSCATED_FISH_1_BRONZE',
        itemName: 'Obfuscated 1 BRONZE',
        itemDisplayName: `${COMMON}${OBFUSCATED}Obfuscated 1 ${DARK_GRAY}${BOLD} BRONZE`,
        npcPrice: 0,
        amountOfMagmaFish: 16,
    },
    {
        itemId: 'OBFUSCATED_FISH_1_SILVER',
        itemName: 'Obfuscated 1 SILVER',
        itemDisplayName: `${COMMON}${OBFUSCATED}Obfuscated 1 ${GRAY}${BOLD} SILVER`,
        npcPrice: 0,
        amountOfMagmaFish: 24,
    },
    {
        itemId: 'OBFUSCATED_FISH_1_GOLD',
        itemName: 'Obfuscated 1 GOLD',
        itemDisplayName: `${COMMON}${OBFUSCATED}Obfuscated 1 ${GOLD}${BOLD} GOLD`,
        npcPrice: 0,
        amountOfMagmaFish: 32,
    },
    {
        itemId: 'OBFUSCATED_FISH_1_DIAMOND',
        itemName: 'Obfuscated 1 DIAMOND',
        itemDisplayName: `${COMMON}${OBFUSCATED}Obfuscated 1 ${AQUA}${BOLD} DIAMOND`,
        npcPrice: 0,
        amountOfMagmaFish: 48,
    },
    {
        itemId: 'OBFUSCATED_FISH_2_BRONZE',
        itemName: 'Obfuscated 2 BRONZE',
        itemDisplayName: `${UNCOMMON}${OBFUSCATED}Obfuscated 2 ${DARK_GRAY}${BOLD} BRONZE`,
        npcPrice: 0,
        amountOfMagmaFish: 40,
    },
    {
        itemId: 'OBFUSCATED_FISH_2_SILVER',
        itemName: 'Obfuscated 2 SILVER',
        itemDisplayName: `${UNCOMMON}${OBFUSCATED}Obfuscated 2 ${GRAY}${BOLD} SILVER`,
        npcPrice: 0,
        amountOfMagmaFish: 60,
    },
    {
        itemId: 'OBFUSCATED_FISH_2_GOLD',
        itemName: 'Obfuscated 2 GOLD',
        itemDisplayName: `${UNCOMMON}${OBFUSCATED}Obfuscated 2 ${GOLD}${BOLD} GOLD`,
        npcPrice: 0,
        amountOfMagmaFish: 80,
    },
    {
        itemId: 'OBFUSCATED_FISH_2_DIAMOND',
        itemName: 'Obfuscated 2 DIAMOND',
        itemDisplayName: `${UNCOMMON}${OBFUSCATED}Obfuscated 2 ${AQUA}${BOLD} DIAMOND`,
        npcPrice: 0,
        amountOfMagmaFish: 120,
    },
    {
        itemId: 'OBFUSCATED_FISH_3_BRONZE',
        itemName: 'Obfuscated 3 BRONZE',
        itemDisplayName: `${RARE}${OBFUSCATED}Obfuscated 3 ${DARK_GRAY}${BOLD} BRONZE`,
        npcPrice: 0,
        amountOfMagmaFish: 400,
    },
    {
        itemId: 'OBFUSCATED_FISH_3_SILVER',
        itemName: 'Obfuscated 3 SILVER',
        itemDisplayName: `${RARE}${OBFUSCATED}Obfuscated 3 ${GRAY}${BOLD} SILVER`,
        npcPrice: 0,
        amountOfMagmaFish: 700,
    },
    {
        itemId: 'OBFUSCATED_FISH_3_GOLD',
        itemName: 'Obfuscated 3 GOLD',
        itemDisplayName: `${RARE}${OBFUSCATED}Obfuscated 3 ${GOLD}${BOLD} GOLD`,
        npcPrice: 0,
        amountOfMagmaFish: 1000,
    },
    {
        itemId: 'OBFUSCATED_FISH_3_DIAMOND',
        itemName: 'Obfuscated 3 DIAMOND',
        itemDisplayName: `${RARE}${OBFUSCATED}Obfuscated 3 ${AQUA}${BOLD} DIAMOND`,
        npcPrice: 0,
        amountOfMagmaFish: 1300,
    },
    {
        itemId: 'BLOBFISH_BRONZE',
        itemName: 'Blobfish BRONZE',
        itemDisplayName: `${COMMON}Blobfish ${DARK_GRAY}${BOLD}BRONZE`,
        npcPrice: 0,
        amountOfMagmaFish: 4,
    },
    {
        itemId: 'BLOBFISH_SILVER',
        itemName: 'Blobfish SILVER',
        itemDisplayName: `${COMMON}Blobfish ${GRAY}${BOLD}SILVER`,
        npcPrice: 0,
        amountOfMagmaFish: 8,
    },
    {
        itemId: 'BLOBFISH_GOLD',
        itemName: 'Blobfish GOLD',
        itemDisplayName: `${COMMON}Blobfish ${GOLD}${BOLD}GOLD`,
        npcPrice: 0,
        amountOfMagmaFish: 12,
    },
    {
        itemId: 'BLOBFISH_DIAMOND',
        itemName: 'Blobfish DIAMOND',
        itemDisplayName: `${COMMON}Blobfish ${AQUA}${BOLD}DIAMOND`,
        npcPrice: 0,
        amountOfMagmaFish: 16,
    },
    {
        itemId: 'GUSHER_BRONZE',
        itemName: 'Gusher BRONZE',
        itemDisplayName: `${COMMON}Gusher ${DARK_GRAY}${BOLD}BRONZE`,
        npcPrice: 0,
        amountOfMagmaFish: 32,
    },
    {
        itemId: 'GUSHER_SILVER',
        itemName: 'Gusher SILVER',
        itemDisplayName: `${COMMON}Gusher ${GRAY}${BOLD}SILVER`,
        npcPrice: 0,
        amountOfMagmaFish: 48,
    },
    {
        itemId: 'GUSHER_GOLD',
        itemName: 'Gusher GOLD',
        itemDisplayName: `${COMMON}Gusher ${GOLD}${BOLD}GOLD`,
        npcPrice: 0,
        amountOfMagmaFish: 64,
    },
    {
        itemId: 'GUSHER_DIAMOND',
        itemName: 'Gusher DIAMOND',
        itemDisplayName: `${COMMON}Gusher ${AQUA}${BOLD}DIAMOND`,
        npcPrice: 0,
        amountOfMagmaFish: 96,
    },
    {
        itemId: 'STEAMING_HOT_FLOUNDER_BRONZE',
        itemName: 'Steaming-Hot Flounder BRONZE',
        itemDisplayName: `${COMMON}Steaming-Hot Flounder ${DARK_GRAY}${BOLD}BRONZE`,
        npcPrice: 0,
        amountOfMagmaFish: 20,
    },
    {
        itemId: 'STEAMING_HOT_FLOUNDER_SILVER',
        itemName: 'Steaming-Hot Flounder SILVER',
        itemDisplayName: `${COMMON}Steaming-Hot Flounder ${GRAY}${BOLD}SILVER`,
        npcPrice: 0,
        amountOfMagmaFish: 28,
    },
    {
        itemId: 'STEAMING_HOT_FLOUNDER_GOLD',
        itemName: 'Steaming-Hot Flounder GOLD',
        itemDisplayName: `${COMMON}Steaming-Hot Flounder ${GOLD}${BOLD}GOLD`,
        npcPrice: 0,
        amountOfMagmaFish: 40,
    },
    {
        itemId: 'STEAMING_HOT_FLOUNDER_DIAMOND',
        itemName: 'Steaming-Hot Flounder DIAMOND',
        itemDisplayName: `${COMMON}Steaming-Hot Flounder ${AQUA}${BOLD}DIAMOND`,
        npcPrice: 0,
        amountOfMagmaFish: 60,
    },
    {
        itemId: 'SULPHUR_SKITTER_BRONZE',
        itemName: 'Sulphur Skitter BRONZE',
        itemDisplayName: `${COMMON}Sulphur Skitter ${DARK_GRAY}${BOLD}BRONZE`,
        npcPrice: 0,
        amountOfMagmaFish: 40,
    },
    {
        itemId: 'SULPHUR_SKITTER_SILVER',
        itemName: 'Sulphur Skitter SILVER',
        itemDisplayName: `${COMMON}Sulphur Skitter ${GRAY}${BOLD}SILVER`,
        npcPrice: 0,
        amountOfMagmaFish: 60,
    },
    {
        itemId: 'SULPHUR_SKITTER_GOLD',
        itemName: 'Sulphur Skitter GOLD',
        itemDisplayName: `${COMMON}Sulphur Skitter ${GOLD}${BOLD}GOLD`,
        npcPrice: 0,
        amountOfMagmaFish: 80,
    },
    {
        itemId: 'SULPHUR_SKITTER_DIAMOND',
        itemName: 'Sulphur Skitter DIAMOND',
        itemDisplayName: `${COMMON}Sulphur Skitter ${AQUA}${BOLD}DIAMOND`,
        npcPrice: 0,
        amountOfMagmaFish: 120,
    },
    {
        itemId: 'FLYFISH_BRONZE',
        itemName: 'Flyfish BRONZE',
        itemDisplayName: `${UNCOMMON}Flyfish ${DARK_GRAY}${BOLD}BRONZE`,
        npcPrice: 0,
        amountOfMagmaFish: 32,
    },
    {
        itemId: 'FLYFISH_SILVER',
        itemName: 'Flyfish SILVER',
        itemDisplayName: `${UNCOMMON}Flyfish ${GRAY}${BOLD}SILVER`,
        npcPrice: 0,
        amountOfMagmaFish: 48,
    },
    {
        itemId: 'FLYFISH_GOLD',
        itemName: 'Flyfish GOLD',
        itemDisplayName: `${UNCOMMON}Flyfish ${GOLD}${BOLD}GOLD`,
        npcPrice: 0,
        amountOfMagmaFish: 64,
    },
    {
        itemId: 'FLYFISH_DIAMOND',
        itemName: 'Flyfish DIAMOND',
        itemDisplayName: `${UNCOMMON}Flyfish ${AQUA}${BOLD}DIAMOND`,
        npcPrice: 0,
        amountOfMagmaFish: 96,
    },
    {
        itemId: 'SLUGFISH_BRONZE',
        itemName: 'Slugfish BRONZE',
        itemDisplayName: `${UNCOMMON}Slugfish ${DARK_GRAY}${BOLD}BRONZE`,
        npcPrice: 0,
        amountOfMagmaFish: 40,
    },
    {
        itemId: 'SLUGFISH_SILVER',
        itemName: 'Slugfish SILVER',
        itemDisplayName: `${UNCOMMON}Slugfish ${GRAY}${BOLD}SILVER`,
        npcPrice: 0,
        amountOfMagmaFish: 60,
    },
    {
        itemId: 'SLUGFISH_GOLD',
        itemName: 'Slugfish GOLD',
        itemDisplayName: `${UNCOMMON}Slugfish ${GOLD}${BOLD}GOLD`,
        npcPrice: 0,
        amountOfMagmaFish: 80,
    },
    {
        itemId: 'SLUGFISH_DIAMOND',
        itemName: 'Slugfish DIAMOND',
        itemDisplayName: `${UNCOMMON}Slugfish ${AQUA}${BOLD}DIAMOND`,
        npcPrice: 0,
        amountOfMagmaFish: 120,
    },
    {
        itemId: 'LAVAHORSE_BRONZE',
        itemName: 'Lavahorse BRONZE',
        itemDisplayName: `${RARE}Lavahorse ${DARK_GRAY}${BOLD}BRONZE`,
        npcPrice: 0,
        amountOfMagmaFish: 12,
    },
    {
        itemId: 'LAVAHORSE_SILVER',
        itemName: 'Lavahorse SILVER',
        itemDisplayName: `${RARE}Lavahorse ${GRAY}${BOLD}SILVER`,
        npcPrice: 0,
        amountOfMagmaFish: 16,
    },
    {
        itemId: 'LAVAHORSE_GOLD',
        itemName: 'Lavahorse GOLD',
        itemDisplayName: `${RARE}Lavahorse ${GOLD}${BOLD}GOLD`,
        npcPrice: 0,
        amountOfMagmaFish: 20,
    },
    {
        itemId: 'LAVAHORSE_DIAMOND',
        itemName: 'Lavahorse DIAMOND',
        itemDisplayName: `${RARE}Lavahorse ${AQUA}${BOLD}DIAMOND`,
        npcPrice: 0,
        amountOfMagmaFish: 24,
    },
    {
        itemId: 'MANA_RAY_BRONZE',
        itemName: 'Mana Ray BRONZE',
        itemDisplayName: `${RARE}Mana Ray ${DARK_GRAY}${BOLD}BRONZE`,
        npcPrice: 0,
        amountOfMagmaFish: 40,
    },
    {
        itemId: 'MANA_RAY_SILVER',
        itemName: 'Mana Ray SILVER',
        itemDisplayName: `${RARE}Mana Ray ${GRAY}${BOLD}SILVER`,
        npcPrice: 0,
        amountOfMagmaFish: 60,
    },
    {
        itemId: 'MANA_RAY_GOLD',
        itemName: 'Mana Ray GOLD',
        itemDisplayName: `${RARE}Mana Ray ${GOLD}${BOLD}GOLD`,
        npcPrice: 0,
        amountOfMagmaFish: 80,
    },
    {
        itemId: 'MANA_RAY_DIAMOND',
        itemName: 'Mana Ray DIAMOND',
        itemDisplayName: `${RARE}Mana Ray ${AQUA}${BOLD}DIAMOND`,
        npcPrice: 0,
        amountOfMagmaFish: 120,
    },
    {
        itemId: 'VANILLE_BRONZE',
        itemName: 'Vanille BRONZE',
        itemDisplayName: `${RARE}Vanille ${DARK_GRAY}${BOLD}BRONZE`,
        npcPrice: 0,
        amountOfMagmaFish: 80,
    },
    {
        itemId: 'VANILLE_SILVER',
        itemName: 'Vanille SILVER',
        itemDisplayName: `${RARE}Vanille ${GRAY}${BOLD}SILVER`,
        npcPrice: 0,
        amountOfMagmaFish: 120,
    },
    {
        itemId: 'VANILLE_GOLD',
        itemName: 'Vanille GOLD',
        itemDisplayName: `${RARE}Vanille ${GOLD}${BOLD}GOLD`,
        npcPrice: 0,
        amountOfMagmaFish: 160,
    },
    {
        itemId: 'VANILLE_DIAMOND',
        itemName: 'Vanille DIAMOND',
        itemDisplayName: `${RARE}Vanille ${AQUA}${BOLD}DIAMOND`,
        npcPrice: 0,
        amountOfMagmaFish: 240,
    },
    {
        itemId: 'KARATE_FISH_BRONZE',
        itemName: 'Karate Fish BRONZE',
        itemDisplayName: `${EPIC}Karate Fish ${DARK_GRAY}${BOLD}BRONZE`,
        npcPrice: 0,
        amountOfMagmaFish: 40,
    },
    {
        itemId: 'KARATE_FISH_SILVER',
        itemName: 'Karate Fish SILVER',
        itemDisplayName: `${EPIC}Karate Fish ${GRAY}${BOLD}SILVER`,
        npcPrice: 0,
        amountOfMagmaFish: 60,
    },
    {
        itemId: 'KARATE_FISH_GOLD',
        itemName: 'Karate Fish GOLD',
        itemDisplayName: `${EPIC}Karate Fish ${GOLD}${BOLD}GOLD`,
        npcPrice: 0,
        amountOfMagmaFish: 80,
    },
    {
        itemId: 'KARATE_FISH_DIAMOND',
        itemName: 'Karate Fish DIAMOND',
        itemDisplayName: `${EPIC}Karate Fish ${AQUA}${BOLD}DIAMOND`,
        npcPrice: 0,
        amountOfMagmaFish: 120,
    },
    {
        itemId: 'MOLDFIN_BRONZE',
        itemName: 'Moldfin BRONZE',
        itemDisplayName: `${EPIC}Moldfin ${DARK_GRAY}${BOLD}BRONZE`,
        npcPrice: 0,
        amountOfMagmaFish: 32,
    },
    {
        itemId: 'MOLDFIN_SILVER',
        itemName: 'Moldfin SILVER',
        itemDisplayName: `${EPIC}Moldfin ${GRAY}${BOLD}SILVER`,
        npcPrice: 0,
        amountOfMagmaFish: 48,
    },
    {
        itemId: 'MOLDFIN_GOLD',
        itemName: 'Moldfin GOLD',
        itemDisplayName: `${EPIC}Moldfin ${GOLD}${BOLD}GOLD`,
        npcPrice: 0,
        amountOfMagmaFish: 64,
    },
    {
        itemId: 'MOLDFIN_DIAMOND',
        itemName: 'Moldfin DIAMOND',
        itemDisplayName: `${EPIC}Moldfin ${AQUA}${BOLD}DIAMOND`,
        npcPrice: 0,
        amountOfMagmaFish: 96,
    },
    {
        itemId: 'SOUL_FISH_BRONZE',
        itemName: 'Soul Fish BRONZE',
        itemDisplayName: `${EPIC}Soul Fish ${DARK_GRAY}${BOLD}BRONZE`,
        npcPrice: 0,
        amountOfMagmaFish: 32,
    },
    {
        itemId: 'SOUL_FISH_SILVER',
        itemName: 'Soul Fish SILVER',
        itemDisplayName: `${EPIC}Soul Fish ${GRAY}${BOLD}SILVER`,
        npcPrice: 0,
        amountOfMagmaFish: 48,
    },
    {
        itemId: 'SOUL_FISH_GOLD',
        itemName: 'Soul Fish GOLD',
        itemDisplayName: `${EPIC}Soul Fish ${GOLD}${BOLD}GOLD`,
        npcPrice: 0,
        amountOfMagmaFish: 64,
    },
    {
        itemId: 'SOUL_FISH_DIAMOND',
        itemName: 'Soul Fish DIAMOND',
        itemDisplayName: `${EPIC}Soul Fish ${AQUA}${BOLD}DIAMOND`,
        npcPrice: 0,
        amountOfMagmaFish: 96,
    },
    {
        itemId: 'SKELETON_FISH_BRONZE',
        itemName: 'Skeleton Fish BRONZE',
        itemDisplayName: `${EPIC}Skeleton Fish ${DARK_GRAY}${BOLD}BRONZE`,
        npcPrice: 0,
        amountOfMagmaFish: 32,
    },
    {
        itemId: 'SKELETON_FISH_SILVER',
        itemName: 'Skeleton Fish SILVER',
        itemDisplayName: `${EPIC}Skeleton Fish ${GRAY}${BOLD}SILVER`,
        npcPrice: 0,
        amountOfMagmaFish: 48,
    },
    {
        itemId: 'SKELETON_FISH_GOLD',
        itemName: 'Skeleton Fish GOLD',
        itemDisplayName: `${EPIC}Skeleton Fish ${GOLD}${BOLD}GOLD`,
        npcPrice: 0,
        amountOfMagmaFish: 64,
    },
    {
        itemId: 'SKELETON_FISH_DIAMOND',
        itemName: 'Skeleton Fish DIAMOND',
        itemDisplayName: `${EPIC}Skeleton Fish ${AQUA}${BOLD}DIAMOND`,
        npcPrice: 0,
        amountOfMagmaFish: 96,
    },
    {
        itemId: 'VOLCANIC_STONEFISH_BRONZE',
        itemName: 'Volcanic Stonefish BRONZE',
        itemDisplayName: `${RARE}Volcanic Stonefish ${DARK_GRAY}${BOLD}BRONZE`,
        npcPrice: 0,
        amountOfMagmaFish: 20,
    },
    {
        itemId: 'VOLCANIC_STONEFISH_SILVER',
        itemName: 'Volcanic Stonefish SILVER',
        itemDisplayName: `${RARE}Volcanic Stonefish ${GRAY}${BOLD}SILVER`,
        npcPrice: 0,
        amountOfMagmaFish: 28,
    },
    {
        itemId: 'VOLCANIC_STONEFISH_GOLD',
        itemName: 'Volcanic Stonefish GOLD',
        itemDisplayName: `${RARE}Volcanic Stonefish ${GOLD}${BOLD}GOLD`,
        npcPrice: 0,
        amountOfMagmaFish: 40,
    },
    {
        itemId: 'VOLCANIC_STONEFISH_DIAMOND',
        itemName: 'Volcanic Stonefish DIAMOND',
        itemDisplayName: `${RARE}Volcanic Stonefish ${AQUA}${BOLD}DIAMOND`,
        npcPrice: 0,
        amountOfMagmaFish: 60,
    },
    {
        itemId: 'GOLDEN_FISH_BRONZE',
        itemName: 'Golden Fish BRONZE',
        itemDisplayName: `${LEGENDARY}Golden Fish ${DARK_GRAY}${BOLD}BRONZE`,
        npcPrice: 0,
        amountOfMagmaFish: 400,
    },
    {
        itemId: 'GOLDEN_FISH_SILVER',
        itemName: 'Golden Fish SILVER',
        itemDisplayName: `${LEGENDARY}Golden Fish ${GRAY}${BOLD}SILVER`,
        npcPrice: 0,
        amountOfMagmaFish: 700,
    },
    {
        itemId: 'GOLDEN_FISH_GOLD',
        itemName: 'Golden Fish GOLD',
        itemDisplayName: `${LEGENDARY}Golden Fish ${GOLD}${BOLD}GOLD`,
        npcPrice: 0,
        amountOfMagmaFish: 1000,
    },
    {
        itemId: 'GOLDEN_FISH_DIAMOND',
        itemName: 'Golden Fish DIAMOND',
        itemDisplayName: `${LEGENDARY}Golden Fish ${AQUA}${BOLD}DIAMOND`,
        npcPrice: 0,
        amountOfMagmaFish: 1300,
    },

    // Dirt

    {
        itemId: 'WORM_THE_FISH',
        itemName: 'Worm the Fish',
        itemDisplayName: `${SPECIAL}Worm the Fish`,
        npcPrice: 0,
        shouldAnnounceRareDrop: true
    },
];